export const colors = {
  COLOR_PRIMARY: "#f96163",
  COLOR_LIGHT: "#fff",
  COLOR_DARK: "#000",
  COLOR_DARK_ALT: "#262626",
};

//  Data for categories filter

export const categories = [
  {
    id: "01",
    image: require("../assets/images/tree.jpg"),
    category: "বীরুৎ",
  },
  {
    id: "02",
    image: require("../assets/images/tree.jpg"),
    category: "গুল্ম",
  },
  {
    id: "03",
    image: require("../assets/images/tree.jpg"),
    category: "আরোহী",
  },
  {
    id: "04",
    image: require("../assets/images/tree.jpg"),
    category: "বৃক্ষ",
  },
];

export const trees = [
  {
    sl: 1,
    bengaliName: "গুল্ম",
    scientificName: "Abelmoschus moschantus (L.) Medic.",
    image: require("../assets/images/tree.jpg"),
    family: "Malvaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ এবং পাতা",
    medicinalUsed:
      "লিউকোডার্মা বা ত্বকে সাদা দাগ, চুলকানি, অ্যাটোনিক ডিসপেপসিয়া বা পেটের পীড়া, মূত্রথলির প্রদাহ এবং হিস্টিরিয়ায় বনঢেঁড়শের বীজ ব্যবহার করা হয়। এ গুল্মের পাতা গনোরিয়া এবং যৌনরোগে ব্যবহৃত হয়।",
  },
  {
    sl: 2,
    bengaliName: "গুল্ম",
    scientificName: "Abroma augusta L.",
    image: require("../assets/images/tree.jpg"),
    family: "Sterculiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং কাণ্ড",
    medicinalUsed:
      "উলটকম্বলের পাতা ও কাণ্ড আমাশয়, দুর্বলতা এবং পেশাবের জ্বালাপোড়া রোগে উপকারী।",
  },
  {
    sl: 3,
    bengaliName: "আরোহী",
    scientificName: "Abrus precatorious L.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ এবং মূল",
    medicinalUsed:
      "এর বীজ ডাইরিয়া, আমাশয় এবং গর্ভপাত ঘটাতে ব্যবহৃত হয়। কাশি, গলা ব্যথা এবং বাত রোগে শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 4,
    bengaliName: "বৃক্ষ",
    scientificName: "Acacia catechu Willd",
    image: require("../assets/images/tree.jpg"),
    family: "Mimosaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল এবং কাণ্ড",
    medicinalUsed:
      "চুলকানি, প্রদাহ, বদহজম, আলসার, লিউকোডর্মা নিরাময় করে এবং দাঁতকে শক্তিশালী করে।",
  },
  {
    sl: 5,
    bengaliName: "বীরুৎ",
    scientificName: "Acalypha indica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "ব্রংকাইটিস, নিউমোনিয়া, হাঁপানি, দাদ এবং ফুসফুসীয় যক্ষ্মা রোগে এ বৃক্ষ উপকারী।",
  },
  {
    sl: 6,
    bengaliName: "বীরুৎ",
    scientificName: " Achyranthes aspera L.",
    image: require("../assets/images/tree.jpg"),
    family: "Amaranthaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "কাশি, নিউমোনিয়া, ত্বকে ফোস্কাপড়া, কিডনিতে পাথর এবং শূলে ব্যবহৃত হয়।",
  },
  {
    sl: 7,
    bengaliName: "বীরুৎ",
    scientificName: "Acorus calamus L.",
    image: require("../assets/images/tree.jpg"),
    family: "Acoraceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম/কন্দ",
    usedPart: "রাইজোম/কন্দ",
    medicinalUsed:
      "এটি গলা ব্যথা, হাঁপানি, রেমিটেন্ট জ্বর, আমাশয়, ব্রঙ্কাইটিস এবং শিশুদের ডায়রিয়া রোগে প্রতিকার হিসাবে ব্যবহৃত হয়।",
  },
  {
    sl: 8,
    bengaliName: "বীরুৎ",
    scientificName: "Adenanthera pavonina L.",
    image: require("../assets/images/tree.jpg"),
    family: "Mimosaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ এবং বাকল",
    medicinalUsed:
      "ফোড়া, কলেরা, সাধারণ পক্ষাঘাত এবং প্রদাহের জন্য এ গাছের বীজ ব্যবহার করা হয়। এর বাকল দীর্ঘস্থায়ী বাত, গেঁটে বাত, পেশাবের সঙ্গে রক্ত যাওয়া এবং রক্তবমি রোগের প্রতিকার।",
  },

  {
    sl: 9,
    bengaliName: "বীরুৎ",
    scientificName: " Aegle marmelos (L.) Corr.",
    image: require("../assets/images/tree.jpg"),
    family: "Rutaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং ফল",
    medicinalUsed:
      "ডায়রিয়া, আমাশয় এবং কোষ্ঠকাঠিন্যে এ গাছের ফল ব্যবহার করা হয়। তাজা পাতার রস চক্ষুপ্রদাহে উপকারী।",
  },
  {
    sl: 10,
    bengaliName: "বীরুৎ",
    scientificName: "Aerva sanguinolenta (L) Bl",
    image: require("../assets/images/tree.jpg"),
    family: "Amaranthaceae",
    category: "বীরুৎ",
    methodOfPropagation: "কাটিং",
    usedPart: "পাতা",
    medicinalUsed: "রক্তপাত নিয়ন্ত্রণে পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 11,
    bengaliName: "বীরুৎ",
    scientificName: " Ageratum conyzoides L.",
    image: require("../assets/images/tree.jpg"),
    family: "Asteraceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed: "এর পাতা দ্রুত কাটা ও ক্ষত নিরাময়ে ব্যবহার করা হয়।",
  },
  {
    sl: 12,
    bengaliName: "বীরুৎ",
    scientificName: "Alangium salvifolium (L. f.) Wang.",
    image: require("../assets/images/tree.jpg"),
    family: "Alangiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূলের বাকল, ফল এবং পাতা",
    medicinalUsed:
      "শিকড়ের বাকল কুষ্ঠ, সিফিলিটিক এবং চর্মরোগে ব্যবহৃত হয়। ফল রেচক, হজমকারী ও কৃমিনাশক। বাতের ব্যাথা নিরসনে এর পাতা উপকারী।",
  },
  {
    sl: 13,
    bengaliName: "বীরুৎ",
    scientificName: "Aloe indica  L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lilliaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "শিকড়",
    medicinalUsed:
      "এর শিকড় মৃদু রেচক, পাইলস, অভ্যাসগত কোষ্ঠকাঠিন্য এবং জন্ডিস নিরসনে উপকারী।",
  },
  {
    sl: 14,
    bengaliName: "বীরুৎ",
    scientificName: "Aloe vera Mill.",
    image: require("../assets/images/tree.jpg"),
    family: "Lilliaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "পাতার ভেতরের অংশ",
    medicinalUsed:
      "পাতার রস বাহ্যিকভাবে পোড়া এবং মচকে যাওয়া রোধে ব্যবহৃত হয়; অভ্যাসগত কোষ্ঠকাঠিন্য, জন্ডিস, হাঁপানি এবং পেটে গ্যাস তৈরি রোধ ইত্যাদি রোগে এটি কার্যকর।",
  },
  {
    sl: 15,
    bengaliName: "বীরুৎ",
    scientificName: " Achyranthes aspera L.",
    image: require("../assets/images/tree.jpg"),
    family: "Amaranthaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "কাশি, নিউমোনিয়া, ত্বকে ফোস্কাপড়া, কিডনিতে পাথর এবং শূলে ব্যবহৃত হয়।",
  },
  {
    sl: 16,
    bengaliName: "বীরুৎ",
    scientificName: "Amaranthus spinosus L.",
    image: require("../assets/images/tree.jpg"),
    family: "Amaranthaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "বুক জ্বালাপোড়া, হ্যালুসিনেশন, কুষ্ঠরোগ, পাইলস, কোষ্ঠকাঠিন্য এবং পেট ফাঁপা রোগে উপকারী।",
  },
  {
    sl: 17,
    bengaliName: "বীরুৎ",
    scientificName: "Amaranthus viridis L.",
    image: require("../assets/images/tree.jpg"),
    family: "Amaranthaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "বুক জ্বালাপোড়া, কুষ্ঠরোগ, ব্রঙ্কাইটিস, পাইলস, সাদাস্রাব এবং কোষ্ঠকাঠিন্যে উপকারী।",
  },
  {
    sl: 18,
    bengaliName: "বীরুৎ",
    scientificName: "Alpinia calcarata Rosc.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "রাইজোম",
    medicinalUsed:
      "রাইজোম মাথাব্যথা, বাতের ব্যথা, গলা ব্যথা, ব্রঙ্কাইটিস এবং পেটেরপীড়া রোগে উপকারী।",
  },
  {
    sl: 19,
    bengaliName: "বীরুৎ",
    scientificName: "Amorphophalus campanutus (Roxb.) BL.ex. Decne.",
    image: require("../assets/images/tree.jpg"),
    family: "Araceae",
    category: "বীরুৎ",
    methodOfPropagation: "কন্দ",
    usedPart: "কন্দ এবং পাতার ডালপালা",
    medicinalUsed:
      "পাইলস, বর্ধিত প্লীহা, টিউমার, হাঁপানি, বমি, পেটে ব্যথা, তীব্র বাত রোগে কন্দ উপকারী। পাতার ডালপালা বিষাক্ত পোকামাকড়ের কামড়ে উপকারী।",
  },
  {
    sl: 20,
    bengaliName: "বীরুৎ",
    scientificName: "Anacardium occidentale L.",
    image: require("../assets/images/tree.jpg"),
    family: "Anacardiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ এবং ছাল",
    medicinalUsed:
      "বীজ আবরণ থেকে আলকাতরা বাহ্যিকভাবে কুষ্ঠরোগ, দাদ, পায়ের গোড়ালিতে ফাটল এবং হাড়ের ক্ষয় রোগে ব্যবহৃত হয়।",
  },
  {
    sl: 21,
    bengaliName: "বীরুৎ",
    scientificName: "Andrographis paniculata (Burm.f.)",
    image: require("../assets/images/tree.jpg"),
    family: "Acanthaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "বৃক্ষটি সাধারণত আমাশয়, পেটেরপীড়া, কোষ্ঠকাঠিন্য, যকৃতের রোগ, জ্বর, মাথাব্যথা এবং চর্মরোগের জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 22,
    bengaliName: "বীরুৎ",
    scientificName: "Annona reticulata L.",
    image: require("../assets/images/tree.jpg"),
    family: "Annonaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং বীজ",
    medicinalUsed:
      "পাকা ফল একটি উত্তম টনিক, শীতল, পরিপক্ক এবং রেচক। বীজ কীটনাশক হিসাবে এবং মাথার উকুন মারার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 23,
    bengaliName: "বীরুৎ",
    scientificName: "Annona squamosa L.",
    image: require("../assets/images/tree.jpg"),
    family: "Annonaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল, বাকল এবং বীজ",
    medicinalUsed:
      "এ গাছের শিকড় শোধনকারী হিসাবে বিবেচিত। বাকল ডায়রিয়া রোগে ব্যবহৃত হয়। বীজ কনজাংটিভা রোগে ব্যবহৃত হয়।",
  },
  {
    sl: 24,
    bengaliName: "বীরুৎ",
    scientificName: "Neolamarckia cadamba (Roxb.) Bosser",
    image: require("../assets/images/tree.jpg"),
    family: "Rubiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল",
    medicinalUsed:
      "বাকল, কাশি, জ্বর, ডায়াবেটিস, কিডনি রোগ এবং আমাশয়ে ব্যবহার করা হয়।",
  },
  {
    sl: 25,
    bengaliName: "বীরুৎ",
    scientificName: "Aquilaria malaccensis Lamk.",
    image: require("../assets/images/tree.jpg"),
    family: "Thymelaeaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "আগর তেল",
    medicinalUsed:
      "আগর তেল ব্যথা উপশম,  উচ্চ রক্তচাপ (এন্টি-স্ট্রেস) নিয়ন্ত্রণ এবং হাঁপানি উপশম করতে ব্যবহৃত হয়।",
  },
  {
    sl: 26,
    bengaliName: "বৃক্ষ",
    scientificName: "Areca catechu L.",
    image: require("../assets/images/tree.jpg"),
    family: "Aracaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "সুপারি অ্যাস্ট্রিঞ্জেন্ট, রেচক, মূত্রবর্ধক, নার্ভাইন এবং কার্ডিওটোনিক; ক্ষুধামন্দা দূর করে এবং স্বাদ উন্নত করে। মাড়ি থেকে রক্তপাত, মূত্রনালীর ব্যাধি এবং দাঁতের ব্যথায় উপকারী।",
  },
  {
    sl: 27,
    bengaliName: "বীরুৎ",
    scientificName: "Argemone maxicana L.",
    image: require("../assets/images/tree.jpg"),
    family: "Papaveraceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ এবং মূল",
    medicinalUsed:
      "বীজ রেচক, ইমেটিক, নেক্রোটিক এবং প্রশমক। কাশি, একজিমা এবং চুলকানিতে এটি ব্যবহৃত হয়। এর মূল দীর্ঘস্থায়ী চর্মরোগে ব্যবহৃত হয়।",
  },
  {
    sl: 28,
    bengaliName: "বীরুৎ",
    scientificName: "Aristolochia indica Cham.",
    image: require("../assets/images/tree.jpg"),
    family: "Aristolochiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং বীজ",
    medicinalUsed:
      "এর মূল ম্যালেরিয়া জ্বর এবং পুরুষত্বহীনতায় ব্যবহৃত হয়। বীজ শোধনকারী; প্রদাহ, পিত্তথলি, শুকনো কাশি, জয়েন্টে ব্যথা এবং শিশুদের পেটেরপীড়ায় উপকারী।",
  },
  {
    sl: 29,
    bengaliName: "গুল্ম",
    scientificName: "Artemisia vulgaris L.",
    image: require("../assets/images/tree.jpg"),
    family: "Asteraceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/ রাইজোম",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা আলসার, চর্মরোগ, আমাশয়, কৃমি এবং মাসিকের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 30,
    bengaliName: "বৃক্ষ",
    scientificName: "Artocarpus lacucha Buch.- Ham.",
    image: require("../assets/images/tree.jpg"),
    family: "Moraceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ এবং বাকল",
    medicinalUsed:
      "ক্ষুধামন্দা, জ্বর, কোষ্ঠকাঠিন্য, চর্মরোগ, ক্ষত ও স্থূলকায় রোগে ব্যবহার করা হয়। বীজ শোধক হিসাবে জনপ্রিয়।",
  },
  {
    sl: 31,
    bengaliName: "আশপরাগাস",
    scientificName: "Asparagus racemosus L.",
    image: require("../assets/images/tree.jpg"),
    family: "Liliaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/ রাইজোম",
    usedPart: "শিকড়",
    medicinalUsed:
      "এর মূল কিডনি ও যকৃতের রোগে, মূত্রনালীর সংক্রমণ, পুরুষত্বহীনতা ও অম্লতার চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 32,
    bengaliName: "বিলিম্বি",
    scientificName: "Averrhoa bilimbi L.",
    image: require("../assets/images/tree.jpg"),
    family: "Averhoeaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং পাতা",
    medicinalUsed:
      "ফলের শরবত তৃষ্ণা দূর করতে, জ্বরজনিত উত্তেজনা, মলদ্বার থেকে রক্তপাত বন্ধ করতে এবং অর্শরোগ দূর করতে ব্যবহৃত হয়। পাতার রস চুলকানি দূর করতে প্রয়োগ করা হয়।",
  },
  {
    sl: 33,
    bengaliName: "আয়াপানা",
    scientificName: "Ayapana triplinervis (M. Vahl) R. King & H. Robinson",
    image: require("../assets/images/tree.jpg"),
    family: "Asteraceae",
    category: "বীরুৎ",
    methodOfPropagation: "কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা জীবাণুনাশক, কফনাশক, লিভার রক্ষাকারী, আলসার প্রতিরোধক এবং ক্ষত নিরাময়ে ব্যবহার করা হয়। পাতার রস সেবন রক্তপাত বন্ধ করে, জ্বর নিরাময় করে, ঘাম বৃদ্ধি করে এবং রক্তকে পাতলা করে।",
  },
  {
    sl: 34,
    bengaliName: "নিম",
    scientificName: "Azadirachta indica A. Juss.",
    image: require("../assets/images/tree.jpg"),
    family: "Meliaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, ফল এবং বাকল।",
    medicinalUsed:
      "নিম গাছের পাতা,ফল এবং বাকল চর্মরোগ, লিভারের কার্যকারিতা উন্নত করতে, রক্তকে ডিটক্সিফাই করতে, জ্বর কমাতে, দাঁতের চিকিৎসা, কাশি, হাঁপানি, আলসার, পাইলস, অন্ত্রের কৃমি, মূত্রনালীর রোগ ইত্যাদিতে ব্যবহৃত হয়।",
  },
  {
    sl: 35,
    bengaliName: "ফটিকা",
    scientificName: "Baccaurea ramiflora Lour.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল",
    medicinalUsed: "বাকল চর্মরোগের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 36,
    bengaliName: "ব্রাহ্মি",
    scientificName: "Bacopa monniera L.",
    image: require("../assets/images/tree.jpg"),
    family: "Scrophulariaceae",
    category: "বীরুৎ",
    methodOfPropagation: "কাটিং",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "এলঝেইমার রোগের জন্য ব্যবহৃত হয় , স্মৃতিশক্তির উন্নতি, উদ্বেগ নিরসন, মনোযোগের ঘাটতি-হাইপারঅ্যাকটিভিটি ডিসঅর্ডার ( ADHD ), অ্যালার্জি, এবং চাপ নিয়ন্ত্রণ করার জন্য একটি সাধারণ টনিক হিসাবে ব্যবহৃত হয়।",
  },
  {
    sl: 37,
    bengaliName: "হিট্টি",
    scientificName: "Baliospermum montanum",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "মূল কোষ্ঠকাঠিন্য, পেটের ব্যথা, সাধারণ আনাসার, পাইলস,কিডনিতে পাথর, কৃমি গঠিত সংক্রমণ, স্ক্যাবিস ও ডার্মাটাইটিসে মূল ব্যবহার করা হয়। হাঁপানির চিকিৎসায় এর পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 38,
    bengaliName: "বন নীলকণ্ঠ",
    scientificName: "Barleria lupulina Lindl.",
    image: require("../assets/images/tree.jpg"),
    family: "Acanthaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "পাতা ও শিকড় চিবালে দাঁতের ব্যথা থেকে মুক্তি পাওয়া যায়। বিষাক্ত পোকামাকড় কামড়ালে এর ব্যাথা থেকে উপশম পেতে এর শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 39,
    bengaliName: "কাঞ্চন",
    scientificName: "Bauhinia purpurea L.",
    image: require("../assets/images/tree.jpg"),
    family: "Caesalpiniaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল, মূল এবং ফুল",
    medicinalUsed:
      "বৃক্ষ ড্রপসি বা শোথরোগ, ব্যথা, বাত, খিঁচুনি, মুখের ঘা, পায়ুপথে রক্তক্ষরণ, এবং বদহজমের কারণে ডায়রিয় ইত্যাদি রোগে ব্যবহার করা হয়।",
  },
  {
    sl: 40,
    bengaliName: "জাফরান",
    scientificName: "Bixa orellana L.",
    image: require("../assets/images/tree.jpg"),
    family: "Bixaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং বীজ",
    medicinalUsed:
      "জন্ডিস ও জ্বরে শিকড় ব্যবহার করা হয়। চর্ম, কুষ্ঠ ও গনোরিয়া রোগে এর বীজ ব্যবহার করা হয়।",
  },
  {
    sl: 41,
    bengaliName: "বিলতি",
    scientificName: "Blumea lacera (Burn.f.) DC.",
    image: require("../assets/images/tree.jpg"),
    family: "Asteraceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "ব্রঙ্কাইটিস, জ্বর এবং জ্বালাপোড়া নিরাময়ে এটি ব্যবহার করা হয়।",
  },
  {
    sl: 42,
    bengaliName: "পুনর্নবা",
    scientificName: "Boerhaavia diffusa L.",
    image: require("../assets/images/tree.jpg"),
    family: "Nyctaginaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "লিভার, গলব্লাডার এবং কিডনি, এবং মূত্রনালীর ব্যাধিতে শিকড় ব্যবহার করা হয়। পাতা জন্ডিস, রক্তশূন্যতা, অ্যাসাইটস অপথালমিয়া এবং ড্রপসিতে উপকারী।",
  },
  {
    sl: 43,
    bengaliName: "শিমুল",
    scientificName: "Bombax ceiba L.",
    image: require("../assets/images/tree.jpg"),
    family: "Bombacaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং আঠা",
    medicinalUsed:
      "কচি মূল আমাশয় ও যৌন রোগে ব্যবহৃত হয়। শিমুল গাছথেকে ঝরা আঠা ডায়রিয়া, কাশি, সাদাশ্রাব এবং শরীর জ্বালাপোড়ায় উপকারী।",
  },
  {
    sl: 44,
    bengaliName: "ডাহু",
    scientificName: "Brugmansia suaveolens (Humb. & Bonpl. ex Willd)",
    image: require("../assets/images/tree.jpg"),
    family: "Solanaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "এর পাতা চা হিসাবে খাওয়া যেতে পারে। রক্তশূন্যতা সহ  বিভিন্ন রোগের চিকিৎসার জন্য শুকনো পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 45,
    bengaliName: "পলাশ",
    scientificName: "Butea monosperma Taub.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "আঠা, বাকল, বীজ, পাতা এবং ফুল",
    medicinalUsed:
      "আমাশয়, পাইলস, সর্দি ও কাশিতে বাকল উপকারী। বাকলের আঠা ডায়রিয়া, আমাশয়, স্টোমাটাইটিস, কাশি এবং কর্নিয়ার অস্পষ্টতায় উপকারী। বীজের পেস্ট গোলকৃমি, ফিতাকৃমির জন্য ভাল প্রতিকার । ফোঁড়া, ব্রন এবং পাইলস রোগে পাতা বাহ্যিকভাবে ব্যবহার করা হয়। ফুল কুষ্ঠ, গেঁটেবাত, চর্মরোগ এবং জ্বালাপোড়া নিরাময় করে।",
  },
  {
    sl: 46,
    bengaliName: "আড়ি",
    scientificName: "Cajanus cajan (L.) Huth.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং বীজ",
    medicinalUsed:
      "এর পাতা মুখের রোগ, পাইলস, জন্ডিস ও নিউমোনিয়ায় ব্যবহৃত হয়। বীজ অন্ত্র এবং মুখের আলসার, টিউমার, ব্রঙ্কাইটিস, হৃদরোগ, পাইলস এবং কাশি নিরাময় করে।",
  },
  {
    sl: 47,
    bengaliName: "আকন্দ",
    scientificName: "Calotropis gigantea (L.) R.Br.",
    image: require("../assets/images/tree.jpg"),
    family: "Asclepiadaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "শিকড়ের ছাল আমাশয়, হাঁপানি, এলিফ্যান্টিয়াসিস এবং সিফিলিসে উপকারী। বাত, ঠাণ্ডার কারণে বুকে ব্যথা, অবশ হয়ে যাওয়া অংশ, চর্মরোগ, ক্ষত এবং ড্রপসি প্রতিরোধে পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 48,
    bengaliName: "মধুকুলি",
    scientificName: "Calotropis procera R. Br.",
    image: require("../assets/images/tree.jpg"),
    family: "Asclepiadaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "মূল, বাকল এবং পাতা",
    medicinalUsed:
      "শিকড়ের বাকল ডায়াফোরটিক, ইমেটিক, অল্টারেটিভ এবং শোধনকারী। আমাশয়, হাঁপানি এবং সিফিলিসে উপকারী।",
  },
  {
    sl: 49,
    bengaliName: "চা",
    scientificName: "Camelia sinensis L.",
    image: require("../assets/images/tree.jpg"),
    family: "Theaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা ভাল ক্ষুধা-উদ্রেককারী, মূত্রবর্ধক এবং দ্রবণকারী; তৃষ্ণা, হেমিক্রেনিয়াস, হৃৎপিণ্ডের ব্যথা, পাইলস এবং প্রদাহে উপকারী।",
  },
  {
    sl: 50,
    bengaliName: "রাজনিগন্ধা",
    scientificName: "Cananga odorata (Lam.) Hook.f.&Thomson",
    image: require("../assets/images/tree.jpg"),
    family: "Annonaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "ফুল",
    medicinalUsed:
      "শুকনো ফুল ম্যালেরিয়ার চিকিৎসায় ব্যবহৃত হয় এবং তাজা ফুল টেনশন কমাতে, রক্তচাপ কমাতে এবং জ্বর কমাতে ব্যবহার করা হয়।",
  },
  {
    sl: 51,
    bengaliName: "আইসি",
    scientificName: "Canarium resiniferum Brace ex King",
    image: require("../assets/images/tree.jpg"),
    family: "Burseraceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "আঠা",
    medicinalUsed:
      "ধূপ সুগন্ধি হিসাবে পোড়ানো হয় এবং বাতজনিত ফোলা কমানোর জন্য চামড়ায় ব্যবহৃত হয়।",
  },
  {
    sl: 52,
    bengaliName: "কানা ইন্ডিকা",
    scientificName: "Canna indica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Cannaceae",
    category: "বীরুৎ",
    methodOfPropagation: "মূল এবং বীজ",
    usedPart:
      "শিকড়, জ্বর, ড্রপসি এবং ডিসপেপসিয়াতে ব্যবহৃত হয়। বীজের রস কানের ব্যথা উপশম করে।",
  },
  {
    sl: 53,
    bengaliName: "কারেয়া",
    scientificName: "Careya arborea Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Lecythidaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল, পাতা এবং ফুল",
    medicinalUsed:
      "শরীরের ফোলা উপশমের জন্য বাকল ব্যবহার করা হয়। কাশি এবং সর্দি নিরাময়ে ফুল ব্যবহার করা হয়।",
  },
  {
    sl: 54,
    bengaliName: "স্যারা",
    scientificName: "Cassia fistula L.",
    image: require("../assets/images/tree.jpg"),
    family: "Caesalpiniaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল, পাতা এবং বীজ",
    medicinalUsed:
      "পাতা ও বীজ কুষ্ঠ, দাদ, পেট ফাঁপা, কোলিক, ডিসপেপসিয়া, কোষ্ঠকাঠিন্য, কাশি, ব্রঙ্কাইটিস, হৃদরোগে উপকারী। বুকে ব্যথা, জয়েন্টের ব্যথা, মাইগ্রেন এবং রক্ত আমাশয়ে শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 55,
    bengaliName: "মদনতি",
    scientificName: "Catharanthus roseus (L.) G. Don.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "পাতা ডায়াবেটিসের নিরাময়ে ব্যবহৃত হয়। মূল বলবৃদ্ধিকারী এবং হজমকারক। এ গাছ থেকে প্রাপ্ত অ্যালকালয়েড ক্যান্সার প্রতিরোধী। লিউকেমিয়া এবং হজকিন রোগের বিরুদ্ধে ব্যবহৃত হয়।",
  },
  {
    sl: 56,
    bengaliName: "শিমুল",
    scientificName: "Ceiba pentandra (L.) Gaertn.",
    image: require("../assets/images/tree.jpg"),
    family: "Malvaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "মূল, বাকল এবং ফল",
    medicinalUsed:
      "শিকড় ফোড়া, ডায়রিয়া, আমাশয়, ঋতুস্রাবে যন্ত্রণা এবং উচ্চ রক্তচাপের চিকিৎসায় ব্যবহৃত হয়। ফল অন্ত্রের পরজীবী এবং পেট-ব্যথার প্রতিকার হিসাবে ব্যবহার করা হয়। দাঁতের ব্যথা এবং মুখের সমস্যা, ক্ষত, ঘা এবং বিষফোড়ার চিকিৎসার জন্য বাকলের রস ব্যবহৃত হয়।",
  },
  {
    sl: 57,
    bengaliName: "থানকুনি",
    scientificName: "Centella asiatica (L.) Urban",
    image: require("../assets/images/tree.jpg"),
    family: "Apiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতার রস জ্বর নিবারক, বলবর্ধক, এবং রক্ত আমাশয়, মুখের ঘা, শ্বেতস্রাব, মূত্র সংক্রমণ, ব্রঙ্কাইটিস, প্রদাহ, খিঁচুনি রোগ, উন্মাদনা এবং চর্মরোগে এটি ব্যবহৃত হয়।",
  },
  {
    sl: 58,
    bengaliName: "বথুয়া",
    scientificName: "Chenopodium album L.",
    image: require("../assets/images/tree.jpg"),
    family: "Chenopodiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "পাইলস, আমাশয়, ক্ষুধামন্দা এবং হেঁচকিতে বৃক্ষ ব্যবহার করা হয়। পাতা কৃমিনাশক, যকৃতের এবং প্লীহা ব্যাধিতে ব্যবহার করা হয়।",
  },
  {
    sl: 59,
    bengaliName: "দুর্বা",
    scientificName: "Chrysopogon zizanioides (L.) Roberty",
    image: require("../assets/images/tree.jpg"),
    family: "Poaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "রুট",
    medicinalUsed:
      "শিকড় ত্বকের চিকিৎসার জন্য ব্যবহৃত হয় । স্নায়ুবিক সমস্যা, দাদের চিকিত্সা, বদহজম এবং ক্ষুধামন্দার চিকিৎসায় এর ব্যবহার রয়েছে।",
  },
  {
    sl: 60,
    bengaliName: "কর্পূর",
    scientificName: "Cinnamomum camphora (L.) J.Presl.",
    image: require("../assets/images/tree.jpg"),
    family: "Lauraceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "উদ্ভিদের নির্যাস",
    medicinalUsed: "কাশি, হাঁপানি, বদহজম, ডায়রিয়া এবং আমাশয়ে ব্যবহৃত হয়।",
  },
  {
    sl: 61,
    bengaliName: "কর্পূরলতা",
    scientificName: "Cinnamomum cecidodaphne Meisn.",
    image: require("../assets/images/tree.jpg"),
    family: "Lauraceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতার রস প্রদাহরোধী, পেশীতে ব্যথা, প্রচন্ড জ্বর, মাথাব্যথা এবং উচ্চ রক্তচাপে ব্যবহার করা হয়।",
  },
  {
    sl: 62,
    bengaliName: "তেজপাতা",
    scientificName: "Cinnamomum tamala Nees.",
    image: require("../assets/images/tree.jpg"),
    family: "Lauraceae",
    category: "বৃক্ষ",
    methodOfPropagation: "কাটিং",
    usedPart: "বাকল এবং পাতা",
    medicinalUsed:
      "পাতার রস চায়ের সাথে মিশিয়ে খেলে সর্দি-কাশি নিরাময় হয়। বাকলের গুঁড়া দাঁতের ক্ষয়, দুর্গন্ধ এবং মাড়ির প্রদাহের জন্য ব্যবহার করা হয়।",
  },
  {
    sl: 63,
    bengaliName: "হাডা",
    scientificName: "Cissus quadrangulais L.",
    image: require("../assets/images/tree.jpg"),
    family: "Vitaceae",
    category: "আরোহী",
    methodOfPropagation: "কান্ড",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "বেদনাদায়ক মাসিক, ডায়রিয়া, আঘাত, পেশী ব্যথা, স্থূআরোহী এবং পাইলসের বিরুদ্ধে বৃক্ষ ব্যবহার করা হয়।",
  },
  {
    sl: 64,
    bengaliName: "জামরুল",
    scientificName: "Clausena heptaphylla Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Rutaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং কান্ড",
    medicinalUsed:
      "কাণ্ডের রস বলবর্ধক, এবং উদ্দীপক । ম্যালেরিয়া জ্বরে মূলের রস ব্যবহার করা হয়।",
  },
  {
    sl: 65,
    bengaliName: "গোলাপী পাতা",
    scientificName: "Clerodendrum viscosum Vent",
    image: require("../assets/images/tree.jpg"),
    family: "Verbenaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "হাঁপানি, টিউমার এবং কিছু চর্মরোগে পাতা ও মূল ব্যবহার করা হয়।",
  },
  {
    sl: 66,
    bengaliName: "অঙ্কুর",
    scientificName: "Clitoria ternatea L.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "রুট",
    medicinalUsed:
      "কর্নিয়া, যক্ষ্মা, এলিফ্যান্টিয়াসিস, মাথাব্যথা, লিউকোডর্মা, ব্যথা, পিত্তথলির প্রদাহ এবং আলসারের জন্য এর শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 67,
    bengaliName: "পোইন",
    scientificName: "Coccinia grandis (L.) Voigt.",
    image: require("../assets/images/tree.jpg"),
    family: "Cucurbitaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা দাদ, স্ক্যাবিস, সাইনাস, ডায়াবেটিস, উচ্চ রক্তচাপ এবং শ্বাসযন্ত্রের রোগের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 68,
    bengaliName: "কফি",
    scientificName: "Coffea arabica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Rubiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "কফি হাঁপানি, বিষক্রিয়া, জ্বর, ফ্লু, মাথাব্যথা, জন্ডিস, ম্যালেরিয়া, মাইগ্রেন, নারকোসিস, নেফ্রোসিস, আফিম বিষক্রিয়া, ঘা এবং ভার্টিগোর জন্য একটি লোকজ প্রতিকার।",
  },
  {
    sl: 69,
    bengaliName: "বন কোলা",
    scientificName: "Costus speciosus Smith.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "রাইজোম",
    medicinalUsed:
      "রাইজোম অ্যাস্ট্রিঞ্জেন্ট এবং কামোদ্দীপক; জ্বর, কাশি, বদহজম, কৃমির সমস্যা, মাসিকের সমস্যা মূত্রনালীর প্রদাহ এবং চর্মরোগে উপকারী।",
  },
  {
    sl: 70,
    bengaliName: "নাগকেশরী",
    scientificName: "Couroupita guianensis Aubl.",
    image: require("../assets/images/tree.jpg"),
    family: "Lecythidaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, ফুল ও ফল",
    medicinalUsed:
      "উচ্চ রক্তচাপ, টিউমার, ব্যথা এবং প্রদাহজনিত চিকিৎসার জন্য এর পাতা ব্যবহার করা হয়। ফলের ভেতরের অংশ ক্ষতকে জীবাণুমুক্ত করতে পারে এবং পাতার রস চর্মরোগের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 71,
    bengaliName: "বরুণ",
    scientificName: "Crateva magna (Lour.) DC.",
    image: require("../assets/images/tree.jpg"),
    family: "Capparidaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ/ রাইজোম",
    usedPart: "পাতা এবং বাকল",
    medicinalUsed:
      "বাত রোগে পাতা ব্যবহার করা হয়। বাকল জ্বর, বমি এবং গ্যাস্ট্রিক রোগে উপকারী; বিশেষ করে কিডনি এবং মূত্রাশয়ের পাথর রোগে উপকারী।",
  },
  {
    sl: 72,
    bengaliName: "জয়ফল",
    scientificName: "Croton tiglium L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "বীজের তেল পেটের রোগ, বদ হজম, কোষ্ঠকাঠিন্য, ড্রপসি, মানসিক সমস্যা, খিঁচুনি, জ্বর, ম্যানিয়া, প্রদাহ এবং ব্রঙ্কাইটিসের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 73,
    bengaliName: "আকাশতুলসি",
    scientificName: "Curculigo orchioides Gaertn.",
    image: require("../assets/images/tree.jpg"),
    family: "Hypoxidaceae",
    category: "বীরুৎ",
    methodOfPropagation: "কন্দ",
    usedPart: "টিউবারাস মূল",
    medicinalUsed:
      "শিকড় তিক্ত, টনিক, মূত্রবর্ধক; ব্রঙ্কাইটিস, অপথালমিয়া, বদহজম, গনোরিয়া, লিউকোরিয়া, ডায়রিয়া এবং জয়েন্টের ব্যথায় উপকারী।",
  },
  {
    sl: 74,
    bengaliName: "নীল হলুদ",
    scientificName: "Curcuma caesia Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "রাইজোম",
    medicinalUsed:
      "রাইজোম এর রস রক্ত আমাশয়, মাথাব্যথা এবং বাতজনিত ব্যথায়  ব্যবহৃত হয়।",
  },
  {
    sl: 75,
    bengaliName: "বন হলুদ",
    scientificName: "Curcuma zedoaria Rosc.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "রাইজোম",
    medicinalUsed:
      "এটি প্রদাহ, ক্ষত, ত্বকের রোগ, ব্যথা, মাসিক নিয়মিতকরণ, হজমের উন্নতি, লিভারের উন্নতি এবং শরীরকে স্বাভাবিক রাখার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 76,
    bengaliName: "আকাশবিলাস",
    scientificName: "Cuscuta reflexa Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Convolnulaceae",
    category: "আরোহী",
    methodOfPropagation: "কান্ড",
    usedPart: "কান্ড",
    medicinalUsed:
      "জন্ডিস, কোষ্ঠকাঠিন্য, পেট ফাঁপা, লিভারের সমস্যা এবং পিত্তজনিত রোগ নিরাময়ে এ আরোহী ব্যবহার করা হয়।",
  },
  {
    sl: 77,
    bengaliName: "লেমন গ্রাস",
    scientificName: "Cymbopogon citratus (DC.) Stapf.",
    image: require("../assets/images/tree.jpg"),
    family: "Poaceae",
    category: "বীরুৎ",
    methodOfPropagation: "উদ্ভিজ্জ",
    usedPart: "পাতা",
    medicinalUsed:
      "বমি, ব্রঙ্কাইটিস, কুষ্ঠ, কলেরা, ডায়রিয়া, গ্যাস, খিঁচুনি, বমি, জ্বর, ফ্লু, এবং মাথাব্যথা এবং অন্যান্য ব্যথা উপশমে এটি উপকারী।",
  },
  {
    sl: 78,
    bengaliName: "যম",
    scientificName: "Cynodon dactylon Pers.",
    image: require("../assets/images/tree.jpg"),
    family: "Poaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ/মূলযুক্ত পার্শ্ব অঙ্কুর",
    usedPart: "রুট",
    medicinalUsed:
      "এ ঘাসের শিকড়, পাইলস, লিউকোরিয়া এবং সেকেন্ডারি সিফিলিসের চিকিৎসায় ও মূত্রবর্ধক হিসেবে ব্যবহার করা হয়। গাছের রস কাটা এবং ক্ষত নিরাময়ে ব্যবহার করা হয়।",
  },
  {
    sl: 79,
    bengaliName: "ভুমি কুশুম",
    scientificName: "Cyperus rotundus L.",
    image: require("../assets/images/tree.jpg"),
    family: "Cyperaceae",
    category: "বীরুৎ",
    methodOfPropagation: "কন্দ",
    usedPart: "কন্দ",
    medicinalUsed:
      "এটি হজমের সমস্যা, পেটে ব্যথা, ক্ষুধামন্দা ডায়রিয়া এবং রক্ত আমাশয়ের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 80,
    bengaliName: "ধতুরা",
    scientificName: "Datura alba Nees.",
    image: require("../assets/images/tree.jpg"),
    family: "Solanaceae",
    category: "ঝোপঝাড়",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং বীজ",
    medicinalUsed:
      "পাতা বাতজনিত ফোলা, কটিবাত, নিতম্ববেদনা, নিউরালজিয়া, টিউমার এবং গ্রন্থির প্রদাহ হিসাবে ব্যবহৃত হয়। পাইলস, চর্মরোগ এবং মস্তিষ্কের রোগের জন্য বীজ ব্যবহার করা হয়।",
  },
  {
    sl: 81,
    bengaliName: "ধতুরা",
    scientificName: "Datura metel L.",
    image: require("../assets/images/tree.jpg"),
    family: "Solanaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং বীজ",
    medicinalUsed:
      "বাতে জনিত কারণে ফোলার জন্য পাতা ব্যবহার করা হয়। ক্ষত নিরাময়ের জন্য বীজ বাহ্যিকভাবে ব্যবহার করা হয়।",
  },
  {
    sl: 82,
    bengaliName: "প্রিয়ঙ্কা",
    scientificName: "Desmodium gangeticum (L.) DC.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "রুট",
    medicinalUsed:
      "টাইফয়েড, জ্বর, পাইলস, হাঁপানি, ব্রঙ্কাইটিস এবং হুপিং কাশিতে শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 83,
    bengaliName: "স্থলপদ্ম",
    scientificName: "Desmodium motorium (Houtt.) Merr.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "সাপে কামড়ানো, হৃদরোগ, ক্ষত নিরাময়, বাতজনিত সমস্যা, ডায়াবেটিস, ত্বকের রোগের চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 84,
    bengaliName: "ছাল",
    scientificName: "Dillenia indica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Dilleniaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "ফল টনিক/বলবর্ধক এবং রেচক; ডায়রিয়া, আমাশয়, পেটের পীড়ায় এবং জ্বরে ব্যবহৃত হয়।",
  },
  {
    sl: 85,
    bengaliName: "কমলাঙ্গুর",
    scientificName: "Dimocarpus longan Lour.",
    image: require("../assets/images/tree.jpg"),
    family: "Sapindaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed: "ফল অনিদ্রা এবং স্নায়ুবিক রোগের জন্য ব্যবহার করা হয়।",
  },
  {
    sl: 86,
    bengaliName: "কাঁচা আলু",
    scientificName: "Dioscorea alata L.",
    image: require("../assets/images/tree.jpg"),
    family: "Dioscoreaceae",
    category: "বীরুৎ",
    methodOfPropagation: "কন্দ",
    usedPart: "কন্দ এবং পাতা",
    medicinalUsed:
      "টিউমার , জ্বর ও গনোরিয়া রোগে কন্দ উপকারী । ফুসকুড়ি ও চুলকানীতে পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 87,
    bengaliName: "গাভি",
    scientificName: "Diospyros malabarica (Desr.) Kostel",
    image: require("../assets/images/tree.jpg"),
    family: "Ebenaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং বাকল",
    medicinalUsed:
      "পাকা ফল ডায়রিয়া, আমাশয়, রক্তের রোগ, গনোরিয়া এবং কুষ্ঠ রোগের চিকিৎসায় উপকারী। বাকল পিত্তজনিত জ্বরের চিকিৎসায় উপকারী।",
  },
  {
    sl: 88,
    bengaliName: "গাভি",
    scientificName: "Diospyros philippensis (Desr.) Gurke",
    image: require("../assets/images/tree.jpg"),
    family: "Ebenaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, বীজ এবং বাকল",
    medicinalUsed:
      "কচি পাতার রস উচ্চ রক্তচাপ, হৃদরোগ, ত্বকের চুলকানি এবং ডায়বেটিসের চিকিৎসায় ব্যবহৃত হয়। বাকল এবং বীজ কাশি, জ্বর, ডায়রিয়া, আমাশয়এ ব্যবহৃত হয়।",
  },
  {
    sl: 89,
    bengaliName: "Zgvj",
    scientificName: "Diospyros cordifolia Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Ebenaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed: "ফল বিষাক্ত; ফোঁড়ার চিকিৎসায় বাহ্যিকভাবে প্রয়োগ করা হয়।",
  },
  {
    sl: 90,
    bengaliName: "Kvj‡Kkx",
    scientificName: "Eclipta alba (L.) Hassk",
    image: require("../assets/images/tree.jpg"),
    family: "Asteraceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "পুরো বীরুৎটি টনিক এবং চুলের রঙ উন্নত করতে ব্যবহার করে এবং চুলের বৃদ্ধিতে ও সহায়তা করে।",
  },
  {
    sl: 91,
    bengaliName: "RjcvB",
    scientificName: "Elaeocarpus floribundus Blume.",
    image: require("../assets/images/tree.jpg"),
    family: "Elaeocarpaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং বাকল",
    medicinalUsed:
      "বাকল এবং পাতার রস মাড়ি এবং আলসারের চিকিত্সার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 92,
    bengaliName: "wMjv",
    scientificName: "Entada pursaetha DC.",
    image: require("../assets/images/tree.jpg"),
    family: "Mimosaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল এবং বীজ",
    medicinalUsed:
      "বাকল চর্মরোগ, জ্বর, ফোঁড়া, এবং তীব্র পিঠের ব্যথার জন্য ব্যবহৃত হয় । বীজের পেস্ট অ্যাক্সিলাতে প্রদাহজনক গ্রন্থি ফুলে যাওয়া, কোমড় ও জয়েন্টের ব্যথায় প্রয়োগ করা হয়।",
  },
  {
    sl: 93,
    bengaliName: "gv›`vi",
    scientificName: "Erythrina variegata L.",
    image: require("../assets/images/tree.jpg"),
    family: "Leguminosae",
    category: "বৃক্ষ",
    methodOfPropagation: "কাটিং",
    usedPart: "পাতা এবং বাকল",
    medicinalUsed:
      "জয়েন্টের ব্যথায় এবং প্রদাহ উপশম করে; আমাশয়, লিভারের সমস্যা, মাঝে মাঝে জ্বর হওয়া, বাত এবং হাঁপানি ও কাশি উপশমে বাকল উপকারী।",
  },
  {
    sl: 94,
    bengaliName: "je½",
    scientificName: "Eugenia caryophyllata Bull.",
    image: require("../assets/images/tree.jpg"),
    family: "Myrtaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "অপরিণত বীজের সাথে ক্যালিসিস",
    medicinalUsed:
      "লবঙ্গ তেল ডায়রিয়া , হার্নিয়া , অন্ত্রের গ্যাস, বমি বমি ভাব এবং বমি এবং নিঃশ্বাসের দুর্গন্ধের জন্য ব্যবহৃত হয় ।",
  },
  {
    sl: 95,
    bengaliName: "`ywaqv",
    scientificName: "Euphorbia hirta L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "এটি ক্যান্সার, ডায়রিয়া, আমাশয়, হাঁপানি, ব্রংকাইটিস, জ্বর, কাশি, অন্ত্রের রোগ, কৃমিজনিত ক্ষত, কিডনিতে পাথর এবং ফোড়ার চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 96,
    bengaliName: "`yaivR",
    scientificName: "Euphorbia tirucalli L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "স্টেম এবং মিল্কি ল্যাটেক্স",
    medicinalUsed:
      "কাণ্ডের রস গনোরিয়া, হুপিং কাশি, হাঁপানি, ড্রপসি, কুষ্ঠ, বর্ধিত প্লীহা, ডিসপেপসিয়া, জন্ডিস, শূল, টিউমার এবং মূত্রাশয়ে পাথরের জন্য উপকারী।",
  },
  {
    sl: 97,
    bengaliName: "K`‡ej",
    scientificName: "Feronia limonia L.",
    image: require("../assets/images/tree.jpg"),
    family: "Rutaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "পাকা ফল ডায়রিয়া এবং আমাশয় রোগের চিকিৎসার জন্য একটি প্রতিকার হিসাবে ব্যবহৃত হয় এবং পাকা ফল গলা সমস্যা, দীর্ঘস্থায়ী কাশি এবং অন্যান্য শ্বাসনালীর রোগের চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 98,
    bengaliName: "wns",
    scientificName: "Ferula assafoetida L.",
    image: require("../assets/images/tree.jpg"),
    family: "Apiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "রুট",
    medicinalUsed:
      "শিকড় বদ হজম, মানসিক রোগ, হৃদরোগ এবং ডায়রিয়ায় ব্যবহার করা হয়।",
  },
  {
    sl: 99,
    bengaliName: "cvBbv‡Mvjv",
    scientificName: "Flacourtia jangomas (Lour.) Raeus.",
    image: require("../assets/images/tree.jpg"),
    family: "Flacourtiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা, বাকল এবং ফল",
    medicinalUsed:
      "পাইলস, মাড়ি থেকে রক্ত পড়া এবং ব্রঙ্কাইটিসে পাতা ব্যবহার করা হয়। বাকল ডায়রিয়া, আমাশয় এবং দাঁতের ব্যথার চিকিৎসায় ব্যবহৃত হয়। বমি বমি ভাব এবং জ্বর উপশমে ফল ব্যবহার করা হয়।",
  },
  {
    sl: 100,
    bengaliName: "KvD",
    scientificName: "Garcinia cowa Roxb",
    image: require("../assets/images/tree.jpg"),
    family: "Clusiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed: "রোদে শুকানো ফল আমাশয় রোগে ব্যবহার করা হয়।",
  },
  {
    sl: 101,
    bengaliName: "wM‡g kvK",
    scientificName: "Glinus oppositifolious (L.)A. DC.",
    image: require("../assets/images/tree.jpg"),
    family: "Molluginaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "তাজা পাতা জয়েন্টের ব্যথায়, প্রদাহ, ডায়রিয়া, অন্ত্রের পরজীবী, জ্বর, ম্যালেরিয়া, ত্বকের ব্যাধি এবং ক্ষত নিরাময়ে ব্যবহার করা হয়।",
  },
  {
    sl: 102,
    bengaliName: "DjUPÛvj",
    scientificName: "Gloriosa superba L.",
    image: require("../assets/images/tree.jpg"),
    family: "Liliaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "রাইজোম",
    medicinalUsed:
      "গেটেবাত, ক্ষত, ফোলা, চর্মরোগ, বিষাক্ত প্রাণীর কামড়, প্রসবকালীন অসুবিধা, অন্ত্রের কৃমি ইত্যাদির চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 103,
    bengaliName: "`vuZb",
    scientificName: "Glycosmis pentaphylla (Retz.) A. DC.",
    image: require("../assets/images/tree.jpg"),
    family: "Rutaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "কান্ড, মূল এবং পাতা",
    medicinalUsed:
      "জ্বর, লিভারের রোগ এবং কৃমিনাশক হিসেবে পাতা ব্যবহার করা হয়। গাছের কান্ড ও মূল আলসারে ব্যবহার করা হয়।",
  },
  {
    sl: 104,
    bengaliName: "Wvqv‡ewUK cøv›U",
    scientificName: "Gynura procumbens",
    family: "Asteraceae",
    category: "বীরুৎ",
    methodOfPropagation: "কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা ব্যবহার করা হয় মাইগ্রেন এর সমস্যা, ডিসপেপসিয়া, কোষ্ঠকাঠিন্য, বাত, , ডায়াবেটিস, আমাশয়, জ্বর, ম্যালেরিয়া, , কিডনিতে পাথর, জয়ের্ট এবং পিঠে ব্যথায় ব্যবহার করা হয়।",
  },
  {
    sl: 105,
    bengaliName: "i‡m‡Kv/ i³‡MvUv",
    scientificName: "Haematocarpus validus (Miers) Bakh.f.ex.Forman",
    image: require("../assets/images/tree.jpg"),
    family: "Menispermaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "উচ্চ রক্তচাপ, আর্থ্রাইটিস, স্নায়বিক সমস্যা ইত্যাদির চিকিৎসার জন্য ফল তাদের ঐতিহ্যবাহী ঔষধি ব্যবহারের জন্য বিখ্যাত।",
  },
  {
    sl: 106,
    bengaliName: "nvwZïuo",
    scientificName: "Heliotropium indicum L.",
    image: require("../assets/images/tree.jpg"),
    family: "Boraginaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "হাঁপানি, আলসার, আমাশয়, ব্রঙ্কাইটিস, চোখ লাল হওয়া, ফোঁড়া, প্রদাহ এবং টিউমারের প্রতিকার হিসাবে পাতা ব্যবহার করা হয়। রাতকানা রোগ নিরাময়ের জন্য শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 107,
    bengaliName: "AbšÍg~j",
    scientificName: "Hemidesmus indicus (L.) R.Br.",
    image: require("../assets/images/tree.jpg"),
    family: "Asclepiadaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "গাছের পাতা জন্ডিস , বাত, শরীর ব্যথা এবং পেটের ব্যথায় উপকারী। শিকড় পেটের পীড়ার চিকিৎসা, ফুসকুড়ি, সিফিলিসের উপসর্গগুলি প্রশমিত করতে এবং গভীর ধ্যানের জন্য ব্যবহার করা হয়।",
  },
  {
    sl: 108,
    bengaliName: "‡g¯Ív/PzKvB",
    scientificName: "Hibiscus cannabinus L.",
    image: require("../assets/images/tree.jpg"),
    family: "Malvaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, ফুল এবং বীজ",
    medicinalUsed:
      "আমাশয়ে পাতা ব্যবহার করা হয়। ফুলের রস অম্লতা নিরাময়ের জন্য জন্য একটি জনপ্রিয় প্রতিকার। বীজ কামোদ্দীপক এবং মোটাতাজাকরণে ব্যবহার করা হয়।",
  },
  {
    sl: 109,
    bengaliName: "Rev",
    scientificName: "Hibiscus rosa-sinensis L.",
    image: require("../assets/images/tree.jpg"),
    family: "Malvaceae",
    category: "গুল্ম",
    methodOfPropagation: "কাটিং",
    usedPart: "পাতা এবং ফুল",
    medicinalUsed:
      "পাতা ব্যথা উপশম, মাথাব্যথা এবং জ্বরের চিকিৎসায় ব্যবহৃত হয়। ফুলের কুঁড়ি শীতলকারক এবং এস্ট্রিনজেন্ট; শরীরের জ্বালাপোড়া, প্রস্রাবের সমস্যা, ধাতুগত দূ্বর্লতা এবং পাইলস রোগ দূর করে। চুল পড়া রোগের জন্য ফুল খুবই কার্যকরী ঘরোয়া প্রতিকার।",
  },
  {
    sl: 110,
    bengaliName: "KziwP",
    scientificName: "Holarrhena pubescence (Buch-Ham.) Wall.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocyanaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল, পাতা এবং বীজ",
    medicinalUsed:
      "বাকল আমাশয়, ডায়রিয়া, জ্বর, পাইলস, কুষ্ঠ ও চর্মরোগ নিরাময় করে। দীর্ঘস্থায়ী ব্রঙ্কাইটিস, কটিবাত, মূত্রত্যাগে সমস্যা, ফোঁড়া এবং আলসার রোগে পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 111,
    bengaliName: "PvjgyMov",
    scientificName: "Hydnocarpus kurzii (King.) Warb.",
    image: require("../assets/images/tree.jpg"),
    family: "Flacourtiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed: "বীজের তেল কুষ্ঠরোগ এবং অন্যান্য চর্মরোগে ব্যবহৃত হয়।",
  },
  {
    sl: 112,
    bengaliName: "ZvjgvLvbv/ Kz‡jLvov",
    scientificName: "Hygrophila auriculata (Schum.) Heyne.",
    image: require("../assets/images/tree.jpg"),
    family: "Acanthaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "পাতার রস টনিক/বলবর্ধক, আমাশয়, মূত্রথলিতে পাথর, কোষ্ঠকাঠিন্য এবং কাশিতে উপকারী।",
  },
  {
    sl: 113,
    bengaliName: "‡ZvKgv",
    scientificName: "Hyptis suaveolens (L.) Poit.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং বীজ",
    medicinalUsed:
      "পাতার রস  ফোঁড়া, একজিমা এবং ডায়াবেটিস রোগের চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 114,
    bengaliName: "k¨vgjZv",
    scientificName: "Ichnocarpus frutescens (L.) R. Br.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা মূল এবং কান্ড",
    medicinalUsed:
      "জ্বর, পেটের পীড়া, ত্বকের রোগ, ডায়াবেটিস এবং মূত্রাশয়ের পাথরের চিকিৎসায় শিকড় ব্যবহার করা হযয়।",
  },
  {
    sl: 115,
    bengaliName: "bxj",
    scientificName: "Indigofera tinctoria L.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, মূল এবং কান্ড",
    medicinalUsed: "হাইড্রোফোবিয়া নিরাময় হিসাবে পাতার রস ব্যবহার করা হয়।",
  },
  {
    sl: 116,
    bengaliName: "fuzBKzgov",
    scientificName: "Ipomoea mauritiana jacq.",
    image: require("../assets/images/tree.jpg"),
    family: "Convolvulaceae",
    category: "টুইনার",
    methodOfPropagation: "বীজ",
    usedPart: "রুট",
    medicinalUsed:
      "শিকড় জ্বর, ব্রঙ্কাইটিস, প্লীহা ও যকৃতের রোগ, মাসিকের সময় অতিরিক্ত রক্তক্ষরণ, দুর্বলতা, ক্লান্তি এবং চর্বি কমাতে ব্যবহৃত হয়।",
  },
  {
    sl: 117,
    bengaliName: "eb Kjwg",
    scientificName: "Ipomoea maxima (L.f.) Don.",
    image: require("../assets/images/tree.jpg"),
    family: "Convolvulaceae",
    category: "বীরুৎ",
    methodOfPropagation: "উদ্ভিজ্জ",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা ডায়াবেটিস, উচ্চ রক্তচাপ, আমাশয়, কোষ্ঠকাঠিন্য, ক্লান্তি, বাত, মেনিনজাইটিস, কিডনি রোগ এবং প্রদাহের চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 118,
    bengaliName: "QvMjLywo/ mvMi Kjwg",
    scientificName: "Ipomoea pes-caprae (L.) R.Br.",
    image: require("../assets/images/tree.jpg"),
    family: "Convolvulaceae",
    category: "আরোহী",
    methodOfPropagation: "উদ্ভিজ্জ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "পাইলস এবং ডায়রিয়ার প্রতিকারের জন্য এ বৃক্ষ ব্যবহার করা হযয়।",
  },
  {
    sl: 119,
    bengaliName: "evN †f‡iÛv/ eb †f‡iÛv",
    scientificName: "Jatropha curcas L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, বীজ এবং বাকল",
    medicinalUsed:
      "বীজের তেল হার্পিস, চুলকানি, একজিমা এবং ফোড়ার ইত্যাদি চর্মরোগের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 120,
    bengaliName: "jvj †f‡iÛv",
    scientificName: "Jatropha gossypifolia L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং বীজ",
    medicinalUsed: "পাতা ফোঁড়া,  একজিমা এবং চুলকানির চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 121,
    bengaliName: "RMrg`b",
    scientificName: "Justacia gendarussa Burm.",
    image: require("../assets/images/tree.jpg"),
    family: "Acanthaceae",
    category: "গুল্ম",
    methodOfPropagation: "কাটিং",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "মাথা ব্যথা, শরীরের একপাশের পক্ষাঘাত এবং মুখের পক্ষাঘাতের চিকিৎসায় পাতার রস খাওয়া হয়।",
  },
  {
    sl: 122,
    bengaliName: "বাসক",
    scientificName: "Justicia adhatoda L.",
    image: require("../assets/images/tree.jpg"),
    family: "Acanthaceae",
    category: "গুল্ম",
    methodOfPropagation: "কাটিং",
    usedPart: "মূল, বাকল এবং পাতা",
    medicinalUsed:
      "বাকল, শিকড় এবং পাতা কাশি, হাঁপানি, শ্বাসকষ্ট এবং ফুসকুড়িতে উপকারী। ম্যালেরিয়া জ্বর এবং ডিপথেরিয়ার চিকিৎসায় শিকড়ের গুড়া ব্যবহার করা হয়।",
  },
  {
    sl: 123,
    bengaliName: "কাচবন",
    scientificName: "Kaempferia galanga L.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম/ বীজ",
    usedPart: "রুট",
    medicinalUsed:
      "শিকড় সর্দি-কাশি, শ্বাস-প্রশ্বাস সমস্যা, অগ্নিমান্দ্য, গ্যাস্ট্রিক এবং মাথাব্যথার চিকিৎসার জন্য ব্যবহৃত হয়। চুলের খুশকি দূরকরণে এটি ব্যবহার করা হয়।",
  },
  {
    sl: 124,
    bengaliName: "পাতাবলু",
    scientificName: "Kalanchoe pinnata (Lam) Pers.",
    image: require("../assets/images/tree.jpg"),
    family: "Crassulaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ/পাতা",
    usedPart: "পাতা",
    medicinalUsed:
      "শ্বাসনালীর সমস্যা, কিডনিতে পাথর, রক্ত আমাশয়, গেঁটেবাত এবং জন্ডিসে এর পাতা উপকারী।",
  },
  {
    sl: 125,
    bengaliName: "মনিকা",
    scientificName: "Lantana camara L.",
    image: require("../assets/images/tree.jpg"),
    family: "Verbenaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "হাম, ম্যালেরিয়া, বাত এবং টিটেনাসের চিকিৎসায় এর পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 126,
    bengaliName: "মেহেদি",
    scientificName: "Lawsonia inermis L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lythraceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "বাকল এবং পাতা",
    medicinalUsed:
      "বাকল লিভারের সমস্যা এবং স্নায়বিক উপসর্গের চিকিৎসায় ব্যবহৃত হয়। মাথাব্যথা, একজিমা, কুষ্ঠ এবং চুলের খুশকিতে পাতার পেস্ট একটি মূল্যবান ঔষধ।",
  },
  {
    sl: 127,
    bengaliName: "লিয়া",
    scientificName: "Leea macrophylla Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Vitaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "রুট",
    medicinalUsed:
      "ক্ষত, ঘা,  কৃমি এবং দাদ রোগের চিকিৎসা হিসেবে বাহ্যিকভাবে শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 128,
    bengaliName: "লিয়া রুবি",
    scientificName: "Leea rubra Blume",
    image: require("../assets/images/tree.jpg"),
    family: "Vitaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং ফল",
    medicinalUsed:
      "শিকড় পেটে ব্যথা, বাত এবং আর্থ্রাইটিসের চিকিৎসায় ব্যবহৃত হয়। চর্মরোগ এবং আমাশয়ের বিরুদ্ধে প্রতিকার হিসাবে এর ফল খাওয়া হয়।",
  },
  {
    sl: 129,
    bengaliName: "গরুমস্তকা",
    scientificName: "Leonurus sibiricus L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "বেদনানাশক এবং অত্যধিক ঋতুস্রাব, প্রসব-পরবর্তী রক্তপাত, শোথ, কিডনির সমস্যা, কিডনিতে পাথর, একজিমা এবং ফোড়ার চিকিৎসায় এ গাছ ব্যবহার করা হয়।",
  },
  {
    sl: 130,
    bengaliName: "শেফা",
    scientificName: "Leucas aspera Link.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতার রস চোখ এবং নাকের ঘার চিকিৎসার জন্য ব্যবহৃত হয়। সোরিয়াসিস এবং অন্যান্য দীর্ঘস্থায়ী ত্বকের রোগে পাতার রস প্রয়োগ করা হয়।",
  },
  {
    sl: 131,
    bengaliName: "বৃহতি",
    scientificName: "Lippia alba (P.Mill.) N.E.Br.",
    image: require("../assets/images/tree.jpg"),
    family: "Verbenaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/নোডাল নরম কাঠের কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "সুগন্ধিযুক্ত পাতা গোসলে, জ্বর এবং তীব্র পেট ব্যথা নিরাময়ে এবং মূত্রাথলি পরিষ্কার করতে ব্যবহৃত হয়।",
  },
  {
    sl: 132,
    bengaliName: "তেজপাতা",
    scientificName: "Litsea monopetala (Roxb.) Pers.",
    image: require("../assets/images/tree.jpg"),
    family: "Lauraceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল এবং পাতা",
    medicinalUsed:
      "ডায়রিয়া, আমাশয় নিরাময়ের জন্য বাকলের নির্যাস ব্যবহার করা হয়। বাতের চিকিৎসায় এর পাতা একটি সাময়িক ঔষধ হিসাবে ব্যবহৃত হয়।",
  },
  {
    sl: 133,
    bengaliName: "গুব",
    scientificName: "Madhuca indica Gmel.",
    image: require("../assets/images/tree.jpg"),
    family: "Sapotaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফুল, বীজ এবং বাকল",
    medicinalUsed:
      "ফুল শীতল, টনিক, প্রশমক এবং বায়ুনাশক; কাশি, সর্দি এবং ব্রঙ্কাইটিসে ব্যবহৃত হয়। চর্মরোগ, বাত, মাথাব্যথা, অভ্যাসগত কোষ্ঠকাঠিন্য এবং পাইলসের চিকিৎসায় বীজ উপকারী। বাকলের রস অ্যাস্ট্রিঞ্জেন্ট এবং টনিক; ক্ষত এবং আলসার নিরাময় করে।",
  },
  {
    sl: 134,
    bengaliName: "দুইআভগ",
    scientificName: "Mangifera sylvatica Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Anacardiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "পশু-পাখীদের চর্মরোগের চিকিৎসায় এর ফল ব্যবহার করা হয়। এর আম থেকে তৈরি তেল কীটনাশক হিসেবে ব্যবহৃত হয়।",
  },
  {
    sl: 135,
    bengaliName: "আরারোট",
    scientificName: "Maranta aurundinacea L.",
    image: require("../assets/images/tree.jpg"),
    family: "Marantaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "রাইজোম",
    medicinalUsed:
      "এটি হজমের সমস্যা, পেট ব্যথা এবং কোষ্ঠকাঠিন্যের চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 136,
    bengaliName: "নিম",
    scientificName: "Melia azadirachta.L.",
    image: require("../assets/images/tree.jpg"),
    family: "Meliaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল, বীজ এবং বাকল",
    medicinalUsed:
      "স্ক্যাবিস, চুলকানি এবং ত্বকের চিকিৎসায় পাতা বাহ্যিকভাবে ব্যবহার করা হয়। বীজ থেকে প্রাপ্ত তেল বাত রোগে ব্যবহৃত হয়। মূলের বাকল দাদ এবং অন্যান্য পরজীবী গঠিত চর্মরোগের বিরুদ্ধে কার্যকর।",
  },
  {
    sl: 137,
    bengaliName: "পুদিনা",
    scientificName: "Mentha arvensis L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "এর পাতা মাথাব্যথা, কাশি, গলা ব্যথা, কোলিক এবং বমির চিকিৎসায় অত্যন্ত কার্যকর। পাতা থেকে তৈরি চা ঐতিহ্যগতভাবে জ্বর, মাথাব্যথা, হজমের ব্যাধির চিকিৎসায় ব্যবহৃত হয়ে আসছে।",
  },
  {
    sl: 138,
    bengaliName: "নাগকেশরী",
    scientificName: "Mesua nagessarium (Burm) Kost.",
    image: require("../assets/images/tree.jpg"),
    family: "Clusiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফুল এবং বীজ",
    medicinalUsed:
      "কাশির জন্যে এর ফুল ব্যবহার করা হয়্। চুলকানি ও বাত রোগে বীজের তেল ব্যবহার করা হয়।",
  },
  {
    sl: 139,
    bengaliName: "চাঁপা",
    scientificName: "Michelia champaca L.",
    image: require("../assets/images/tree.jpg"),
    family: "Magnoliaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফুল, বীজ এবং বাকল",
    medicinalUsed:
      "ফুল ও ফল অগ্নিমান্দ্য, বমি বমি ভাব, জ্বর, কিডনি রোগ এবং গনোরিয়া রোগে ব্যবহৃত হয়। জ্বরের জন্য এর বাকল ব্যবহার করা হয়। বাত রোগের জন্য এবং পায়ের তলায় ফাটল নিরাময়ের জন্য বীজ ব্যবহার করা হয়।",
  },
  {
    sl: 140,
    bengaliName: "আমিনা",
    scientificName: "Mikania micrantha Kunth.",
    image: require("../assets/images/tree.jpg"),
    family: "Asteraceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা  চুলকানি এবং ক্ষতের জন্য পোল্টিস হিসাবে ব্যবহৃত হয়। গ্যাস্ট্রিক আলসার সহ পেট এবং অন্ত্রের  চিকিৎসায় এটি ব্যবহার করা হয়।",
  },
  {
    sl: 141,
    bengaliName: "বকুল",
    scientificName: "Mimosops elengi L.",
    image: require("../assets/images/tree.jpg"),
    family: "Sapotaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, ফল, বাকল এবং বীজ",
    medicinalUsed:
      "বাকল টনিক, অ্যাস্ট্রিঞ্জেন্ট এবং জ্বর কমাতে ব্যবহৃত হয়। পাতা মাথাব্যথা, দাঁতের ব্যথা, ক্ষত এবং চোখের ব্যথার চিকিৎসার জন্য ব্যবহৃত হয়।  নাক ও মুখের সংক্রমণ নিরাময়ের জন্য এর ধূয়া উপকারী। ফলের মজ্জা দীর্ঘস্থায়ী আমাশয় নিরাময়ে ব্যবহৃত হয়। শুকনো ফুলের গুঁড়া ব্রেন টনিক হিসেবে ব্যবহৃত হয়। অস্থির কোষ্ঠকাঠিন্য নিরাময়ে বীজ ব্যবহার করা হয়।",
  },
  {
    sl: 142,
    bengaliName: "ছিটা শোল",
    scientificName: "Mimosa invisa Martius ex Colla.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "এটি ফোড়া, আলসার, ক্ষত, ছত্রাক, কাটা এবং পাইলসের উপর বাহ্যিকভাবে প্রয়োগ করা যেতে পারে । এটি মেনোরেজিয়া, অত্যধিক জরায়ুর রক্তপাত এবং রক্ত, শ্লেষ্মা এবং পাইলসের সাথে আমাশয়ের মতো রক্তক্ষরণজনিত রোগের চিকিৎসায় কার্যকর।",
  },
  {
    sl: 143,
    bengaliName: "লজ্জা ফুল",
    scientificName: "Mimosa pudica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "এর শিকড় কুষ্ঠ, আমাশয়, প্রদাহ, জ্বালাপোড়া, হাঁপানি এবং জন্ডিস নিরাময়ে ব্যবহৃত হয়। পাইলস ও ফিস্টুলায় এর পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 144,
    bengaliName: "মোরিংগা",
    scientificName: "Moringa oleifera Lamk.",
    image: require("../assets/images/tree.jpg"),
    family: "Moringaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল, পাতা এবং বীজ",
    medicinalUsed:
      "বাকল পক্ষাঘাতগ্রস্থ ক্ষত, মাঝে মাঝে জ্বর, পাইলস এবং হিস্টিরিয়ায় ব্যবহৃত হয়। পাতা হেঁচকিতে উপকারী এবং ব্যথা দূর করে। বীজ ভেনারেলে এফেকশন এ ব্যবহার করা হয়।",
  },
  {
    sl: 145,
    bengaliName: "শাতকলা",
    scientificName: "Morus indica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Moraceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং মূল",
    medicinalUsed:
      "ফল রক্তের টনিক হিসাবে দেওয়া হয়। রক্তশূন্যতা, অকালে চুল পাকা, ক্যানকার ঘা, পোড়া, পাইলস, মাথা ঘোরা এবং অনিদ্রা এর ফল ব্যবহার করা হয়।",
  },
  {
    sl: 146,
    bengaliName: "কপিকচু",
    scientificName: "Mucuna pruriens (L.) DC.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "টুইনার",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "বীজ অনিদ্রা, বিষণ্নতার চিকিৎসার জন্য ব্যবহার করা হয়, দীর্ঘ সময় ঘুমাতে এবং স্তন্যদায়ী মাযেদের  দুধ বৃদ্ধি করে ।",
  },
  {
    sl: 147,
    bengaliName: "কুড়ি",
    scientificName: "Murraya koenigii (L.) Spreng.",
    image: require("../assets/images/tree.jpg"),
    family: "Rutaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "ডায়াবেটিস, ফোঁড়া, এবং ত্বকের ক্ষত সারাতে পাতা ব্যবহার করা হয়। এটি পরিপাকতন্ত্রের জন্যও ভালো। এর প্রতিদিনের ব্যবহার চুলের অকালে পেকে যাওয়া রোধ করে।",
  },
  {
    sl: 148,
    bengaliName: "কারু",
    scientificName: "Murraya paniculata (L.) Jack",
    image: require("../assets/images/tree.jpg"),
    family: "Rutaceae",
    category: "গুল্ম",
    methodOfPropagation: "শাখা কাটা/বীজ",
    usedPart: "পাতা এবং বাকল",
    medicinalUsed:
      "পাতা শরীরের কোন অংশ ফোলা, ডায়রিয়া, ত্বকের রোগ, ত্বকের জ্বালা এবং দাঁতের ব্যথার চিকিৎসায় ব্যবহৃত হয়। এর বাকল জ্বর, যৌনরোগ, অন্ত্রের কৃমি এবং আমাশয়ের বিরুদ্ধে ব্যবহৃত হয়।",
  },
  {
    sl: 149,
    bengaliName: "জায়ফল",
    scientificName: "Myristica fragrans Houtt.",
    image: require("../assets/images/tree.jpg"),
    family: "Myristicaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "ডায়রিয়া, আমাশয়, বমি, পেটের পীড়া, বদহজম, বাত এবং পেটের ব্যথার চিকিৎসায় বীজ ব্যবহার করা হয়।",
  },
  {
    sl: 150,
    bengaliName: "বকুল",
    scientificName: "Neolamarckia cadamba (Roxb.) Bosser",
    image: require("../assets/images/tree.jpg"),
    family: "Rubiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল",
    medicinalUsed:
      "এর বাকল কাশি, জ্বর, ডায়াবেটিস, কিডনি রোগ এবং আমাশয়ে ব্যবহার করা হয়।",
  },
  {
    sl: 151,
    bengaliName: "কানের দোম",
    scientificName: "Nerium oleander L.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "মূল, পাতা এবং ফুল",
    medicinalUsed:
      "পাতার রস ফোলা, চুলকানি এবং চুল পড়া কমাতে ব্যবহার করা হয়। এর ফুল প্রদাহ, পেশী এবং জয়েন্টের দীর্ঘস্থায়ী ব্যথা, পিঠে ব্যথা, মাথাব্যথা এবং খোসপাঁচড়ার জন্য ভাল। শিকড় চর্মরোগ ও কুষ্ঠরোগে ব্যবহার করা হয়।",
  },
  {
    sl: 152,
    bengaliName: "সাদাপাতি",
    scientificName: "Nerium odoratum Lam.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "স্ক্যাবিস এবং কৃমির চিকিৎসায় পাতার রস বাহ্যিকভাবে প্রয়োগ করা হয়। মূলের বাকল থেকে তৈরি তেল কুষ্ঠ ও চর্মরোগের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 153,
    bengaliName: "গজ পাতা",
    scientificName: "Ocimum americanum L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "এ  গুল্ম কার্মিনেটিভ, ডায়াফোরটিক এবং উদ্দীপক; ঠাণ্ডা, কাশি, সদি এবং ব্রঙ্কাইটিসে ব্যবহৃত হয়। পাতার রস নাক দিয়ে রক্ত পড়া এবং ম্যালেরিয়াল জ্বর পরীক্ষা করার জন্য ব্যবহার করা হয়।",
  },
  {
    sl: 154,
    bengaliName: "বাসিল",
    scientificName: "Ocimum basilicum L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "গুল্মটি গনোরিয়া, দীর্ঘস্থায়ী আমাশয়, দাদ, কাশি, নাকের মায়োসিস, লিভার এবং প্লীহার রোগে ব্যবহৃত হযয়। এর রস পরজীবীনাশক এবং অ্যান্টিসেপটিক এবং স্থানীয় অ্যানেস্থেশিয়া তৈরি করে।",
  },
  {
    sl: 155,
    bengaliName: "দুর্বীপ",
    scientificName: "Ocimum gratissimum L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং বীজ",
    medicinalUsed:
      "পাতার রস ও বীজ গনোরিয়া, মাথাব্যথা, স্নায়বিক রোগ, অল্প প্রস্রাব, জ্বর এবং ইনফ্লুয়েঞ্জা রোগে উপকারী। পাতার রস ধাতু দুর্বলতা এবং অনিয়মিত মাসিক রোগে উপকারী।",
  },
  {
    sl: 156,
    bengaliName: "তুলসী",
    scientificName: "Ocimum tenuiflorum L.",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতার রস ব্রঙ্কাইটিস, শ্বাসনালীর হাঁপানি, ম্যালেরিয়া, ডায়রিয়া, আমাশয়, চর্মরোগ, বাত, চোখের রোগ, দীর্ঘস্থায়ী জ্বর এবং পোকামাকড়ের কামড়ের চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 157,
    bengaliName: "পিটা কাঁঠাল",
    scientificName: "Opuntia dillenii (Ker.-Gawl.) Haw.",
    image: require("../assets/images/tree.jpg"),
    family: "Cactaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ / উদ্ভিজ্জ",
    usedPart: "পাতা",
    medicinalUsed:
      "পিত্তথলির সমস্যা, জ্বালাপোড়া, লিউকোডর্মা, প্রস্রাবের সমস্যা,, টিউমার, চেতনা হ্রাস, পাইলস, প্রদাহ, রক্তাল্পতা, আলসার এবং প্লীহা বড় হয়ে যাওয়া নিরাময়ে পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 158,
    bengaliName: "পিতচূর",
    scientificName: "Oroxylum indicum (L.) Vent.",
    image: require("../assets/images/tree.jpg"),
    family: "Bignoniaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং মূলের ছাল",
    medicinalUsed:
      "ফল ত্বকের জন্যে উপকারী। ফল ক্ষত নিরাময় করে এবং রক্তকে বিশুদ্ধ করে। শিকড়ের বাকল ক্ষুধামন্দা, রিউমাটয়েড আর্থ্রাইটিস, সর্দি-কাশি, ও জ্বরে ব্যবহৃত হয়।",
  },
  {
    sl: 159,
    bengaliName: "চুকাঁদরী",
    scientificName: "Oxalis corniculata L.",
    image: require("../assets/images/tree.jpg"),
    family: "Oxalidaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো গাছ",
    medicinalUsed:
      "পুরো আরোহী গাছটি ইনফ্লুয়েঞ্জা, জ্বর, মূত্রনালীর সংক্রমণ, এন্ট্রাইটিস, ডায়রিয়া, মচকে যাওয়া এবং বিষাক্ত সাপের কামড়ের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 160,
    bengaliName: "পাদেরি",
    scientificName: "Paederia foetida L.",
    image: require("../assets/images/tree.jpg"),
    family: "Rubiaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতা লিভার এবং পেটের সমস্যায়, পেটে ব্যথা, শূল, খিঁচুনি, পেট ফাঁপা এবং আমাশয় রোগে ব্যবহার করা হয়; এবং বাত এবং গাউটের চিকিৎসার জন্যও ব্যবহৃত হয়। পাতা রান্না করা হয় এবং বদহজম এবং ডায়রিয়ার প্রতিকার হিসাবে নেওয়া হয়।",
  },
  {
    sl: 161,
    bengaliName: "আমলতাস",
    scientificName: "Pandanus amaryllifolius Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Pandanaceae",
    category: "বীরুৎ",
    methodOfPropagation: "পাশ্বর্ীয় অঙ্কুর চুষা/কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "পাতার রস বুকে ব্যথা, জ্বর এবং বাতের ব্যথা কমাতে ব্যবহৃত হয়। পাতার রস অস্থিরতা কমাতে ব্যবহৃত হয়।",
  },
  {
    sl: 162,
    bengaliName: "পাসফুলা",
    scientificName: "Passiflora edulis Sims",
    image: require("../assets/images/tree.jpg"),
    family: "Passifloraceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং ফুল",
    medicinalUsed:
      "এর ফলে আয়রন, পটাসিয়াম, জিঙ্ক এবং ম্যাঙ্গানিজের উল্লেখযোগ্য পরিমানে উপাদান রয়েছে যা কার্বোহাইড্রেটের ভাঙ্গন  এবং শোষণকে হ্রাস করে, ইনসুলিনের প্রতি পেশী এবং অ্যাডিপোজ টিস্যুর সংবেদনশীলতা বাড়ায়। এছাড়াও এর  ফুল স্নায়ুবিক ব্যাধি, শ্বাসনালীর সমস্যা, বাত, হাঁপানি, অনিদ্রা, গ্যাস্ট্রোইনটেস্টাইনাল ব্যাধি এবং মেনোপজের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 163,
    bengaliName: "ছাগলপাতা",
    scientificName: "Pedilanthes tithymaliodes (L.) Poit",
    image: require("../assets/images/tree.jpg"),
    family: "Acanthaceae",
    category: "গুল্ম",
    methodOfPropagation: "কাটিং",
    usedPart: "পুরো গুল্ম",
    medicinalUsed:
      "পুরো গুল্ম জ্বর, কাশি, হজমের সমস্যা এবং শ্বাসকষ্টের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 164,
    bengaliName: "পাশফুলা",
    scientificName: "Persicaria hydropiper (L.) Spach",
    image: require("../assets/images/tree.jpg"),
    family: "Polygonaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো গুল্ম",
    medicinalUsed:
      "পুরো গুল্ম বর্ধিত লিভার, ক্ষত, অন্ত্রের কৃমি, চর্মরোগ, বেদনাদায়ক ফোড়া এবং অকাল গর্ভপাতের জন্য ব্যবহৃত হয়। শিকড় উদ্দীপক এবং টনিক।",
  },
  {
    sl: 165,
    bengaliName: "চুকাঁদর",
    scientificName: "Persicaria orientalis (L.) Spach",
    image: require("../assets/images/tree.jpg"),
    family: "Polygonaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো গুল্ম",
    medicinalUsed:
      "গুল্ম একটি ভাল টনিক। এর পাতা মাসিকের সময় অতিরিক্ত রক্তকরণ, সন্তান প্রশবের পর অতিরিক্ত রক্তক্ষরণ, এবং ক্ষত নিরাময়ের জন্য ব্যবহৃত হয়। দাতের মাড়ি থেকে রক্ত পড়া, কাটা ও ক্ষতস্থান থেকে রক্তক্ষরণে এটি ব্যবহার করা হয়।",
  },
  {
    sl: 166,
    bengaliName: "AieiB",
    scientificName: "Phyllanthus acidus (L.)  Skiels.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং ফল",
    medicinalUsed:
      "ফল লিভারের টনিক হিসাবে রক্তকে সমৃদ্ধ করতে, ব্রঙ্কাইটিস, পিত্তথলি এবং পাইলসের চিকিৎসায় ব্যবহৃত হয়। চর্মরোগ নিরাময়ে বিশেষ করে চুলকানি থেকে মুক্তি দিতে এর শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 167,
    bengaliName: "fuzB Avgjv",
    scientificName: "Phyllanthus amarus  Schum.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "তরুণ কোমল অঙ্কুর দীর্ঘস্থায়ী আমাশয় নিরাময়ে উপকারী। পেটের তীব্র ব্যথায় পাতার রস পান করা হয়। তাজা শিকড় জন্ডিসে উপকারী।",
  },
  {
    sl: 168,
    bengaliName: "AvgjwK",
    scientificName: "Phyllanthus emblica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "ফল বমি নিরসনে উপকারী; যকৃতের রোগ, ত্বকের সমস্যা এবং লিউকোরিয়া রোগে এ বৃক্ষের ফল ব্যবহার করা হয়।",
  },
  {
    sl: 169,
    bengaliName: "dzUwK",
    scientificName: "Physalis minima L.",
    image: require("../assets/images/tree.jpg"),
    family: "Solanaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা এবং ফল",
    medicinalUsed:
      "পাতার রস পানি ও সরিষার তেলের সাথে মিশিয়ে কানের ব্যথার প্রতিকার হিসেবে ব্যবহার করা হয়। ফল টনিক, মূত্রবর্ধক, এবং শোধনকারী; গনোরিয়া এবং প্লীহা ব্যাধিতে ব্যবহৃত হয়।",
  },
  {
    sl: 170,
    bengaliName: "Aj ¯úvBwmm/পিমেন্টা",
    scientificName: "Pimenta dioca (L.) Merr.",
    image: require("../assets/images/tree.jpg"),
    family: "Mrytaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "এর তেল বদহজম, ডায়রিয়া এবং স্নায়বিক ক্লান্তির চিকিৎসায় ব্যবহৃত হয়। বাহ্যিকভাবে এটি বুকের সংক্রমণ, পেশীতে ব্যথা এবং অন্যান্য ব্যথার চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 171,
    bengaliName: "cvb",
    scientificName: "Piper betle L.",
    image: require("../assets/images/tree.jpg"),
    family: "Piperaceae",
    category: "আরোহী",
    methodOfPropagation: "রাইজোম/কাটিং",
    usedPart: "পাতা",
    medicinalUsed:
      "বদহজম, পেটব্যথা, ডায়রিয়া, ফুসফুসের প্রদাহ, কন্ঠনালীর প্রদাহ, মাথাব্যথা এবং কাশি নিরাময়ে এর পাতা ব্যবহার করা হয়। সরিষার তেলে ডুবানো পাতা শিশুদের জন্য সাপোজিটরি হিসাবে প্রয়োগ করা হয়।",
  },
  {
    sl: 172,
    bengaliName: "wccyj",
    scientificName: "Piper longum L.",
    image: require("../assets/images/tree.jpg"),
    family: "Piperaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "ফল",
    medicinalUsed:
      "অগ্নিমান্দ্য, ক্রনিক ব্রঙ্কাইটিস, কাশি, সর্দি এবং জয়েন্টে ব্যথার চিকিৎসায় এর ফল ব্যবহার করা হয়।",
  },
  {
    sl: 173,
    bengaliName: "‡MvjgwiP",
    scientificName: "Piper nigrum L.",
    image: require("../assets/images/tree.jpg"),
    family: "Piperaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "ফল",
    medicinalUsed:
      "সর্দি, কাশি, জ্বর, হাঁপানি, গলা ব্যথা এবং দাঁতের ব্যথা ও চর্মরোগের চিকিৎসায় এর ফল ব্যবহার করা হয়।",
  },
  {
    sl: 174,
    bengaliName: "‰P-Svj",
    scientificName: "Piper retrofractum Vahl",
    image: require("../assets/images/tree.jpg"),
    family: "Piperaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "মূল এবং ফল",
    medicinalUsed:
      "সর্দি, কাশি, পাইলস এবং ক্ষুধা ও রুচি বাড়াতে এর ফল ব্যবহার করা হয়। শিকড় হাঁপানি, ব্রংকাইটিস রোগে উপকারী।",
  },
  {
    sl: 175,
    bengaliName: "mvjvZcvZv",
    scientificName: "Plectranthus amboinikus",
    image: require("../assets/images/tree.jpg"),
    family: "Lamiaceae",
    category: "বীরুৎ",
    methodOfPropagation: "কাটিং/রাইজোম",
    usedPart: "পাতা",
    medicinalUsed:
      "এর পাতা মূত্র সংক্রান্ত রোগ, ব্রংকাইটিস, হাপানি, পাইলস, গনোরিয়া রোগে উপকারী।",
  },
  {
    sl: 176,
    bengaliName: "jvjwPZv",
    scientificName: "Plumbago indica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Plumbaginaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "শিকড়",
    medicinalUsed:
      "হেপাটাইটিস, ডিসপেপসিয়া, পেট ফাঁপা, পাইলস, লিউকোডার্মা, কুষ্ঠ ও আনাসারকাতে শিকড় ব্যবহার করা হয়।",
  },
  {
    sl: 177,
    bengaliName: "‡k^ZwPZv",
    scientificName: "Plumbago zeylanica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Plumbaginaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "শিকড়",
    medicinalUsed:
      "শিকড় অকার্যকর, আনাসারকা, খোসপাঁচড়া ও চর্মরোগে ব্যবহৃত হয়। এটি হজম শক্তি বাড়ায় এবং ক্ষুধা বাড়ায়।",
  },
  {
    sl: 178,
    bengaliName: "KvV‡Mvjvc",
    scientificName: "Plumeria alba L.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "মূল এবং বাকল",
    medicinalUsed:
      "ব্লেনোরেজিয়া, হারপিস এবং সিফিলিসের চিকিৎসায় শিকড় ব্যবহার করা হয়। বাকলের রস গনোরিয়া এবং যৌনাঙ্গে ঘা এর জন্য  একটি কার্যকর ঔষধ হিসাবে বিবেচিত হয়।",
  },
  {
    sl: 179,
    bengaliName: "Mwbqvwi/ Mv¤^vix",
    scientificName: "Premna integrifolia L.",
    image: require("../assets/images/tree.jpg"),
    family: "Verbenaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "গাছের রস বাত এবং স্নায়বিক রোগে ব্যবহৃত হয়। পাতার রস জ্বর, অগ্নিমান্দ্য এবং পেট ফাঁপা, গনোরিয়া, খিঁচুনি, বাত এবং স্নায়ুতন্ত্রের রোগে ব্যবহৃত হয়। লিভারের রোগের জন্য শিকড় ভাল; পাইলস, কোষ্ঠকাঠিন্য এবং ব্রঙ্কাইটিস রোগেও ব্যবহার করা হয়।",
  },
  {
    sl: 180,
    bengaliName: "Avjy‡evLviv",
    scientificName: "Prunus salicina Lindl",
    image: require("../assets/images/tree.jpg"),
    family: "Rosaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "ফল তৃষ্ণা নিবারণের জন্য ভালো এবং আর্থ্রাইটিসের চিকিৎসায় ব্যবহার করা হয়।",
  },
  {
    sl: 181,
    bengaliName: "ey×-bvwi‡Kj/ bvwi‡Kjx",
    scientificName: "Pterygota alata (Roxb.) .Br.",
    image: require("../assets/images/tree.jpg"),
    family: "Sterculiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "এর বীজে মাদকদ্রব্যের বৈশিষ্ট্য রয়েছে এবং এটি আফিমের বিকল্প হিসেবে ব্যবহৃত হয়।",
  },
  {
    sl: 182,
    bengaliName: "cyÎÄxe/ A‡KU",
    scientificName: "Putronjiva roxburghii",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "বীজ ও পাতার রস লিভারের রোগ, ঠান্ডা, জ্বর, ব্যথায় উপকারী। বীজের গুড়া মাথা ও হাটুর ব্যথায় ব্যবহার করা হয়।",
  },
  {
    sl: 183,
    bengaliName: "mc©MÜv/ ‡QvUPv`i",
    scientificName: "Rauwolfia serpentina (L.) Benth.ex Kurz.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "শিকড়",
    medicinalUsed:
      "শিকড় উচ্চ রক্তচাপ, অনিদ্রা, হিস্টিরিয়া এবং উচ্চ রক্তচাপ রোগীদের জন্য মূল্যবান প্রতিকার।",
  },
  {
    sl: 184,
    bengaliName: "mc©MÜv/ eoPv`i",
    scientificName: "Rauwolfia tetraphylla L.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "শিকড়",
    medicinalUsed:
      "উদ্বেগ, উত্তেজনা, উন্মাদনা, অনিদ্রা এবং মৃগীরোগের মতো স্নায়ুজনিত ব্যাধিগুলির উপশমের জন্য শিকড় ব্যবহার করা হয়। জরায়ুর সংকোচন বাড়ানোর জন্য ডিকোশন ব্যবহার করা হয়।",
  },
  {
    sl: 185,
    bengaliName: "‡f‡iÛv/ †iox",
    scientificName: "Ricinus communis L.",
    image: require("../assets/images/tree.jpg"),
    family: "Euphorbiaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ এবং পাতা",
    medicinalUsed:
      "বীজের তেল বাহ্যিকভাবে বাতের ব্যথা, জয়েন্টে ব্যথা, পক্ষাঘাত এবং অভ্যন্তরীণভাবে কোষ্ঠকাঠিন্যের চিকিৎসায় জন্য ব্যবহৃত হয়। মাথাব্যথা উপশম করতে এবং ফোঁড়া নিরাময়ের জন্য পাতা পোল্টিস হিসাবে ব্যবহার করা হয়।",
  },
  {
    sl: 186,
    bengaliName: "‡NvovP°i",
    scientificName: "Sansevieria kirkii Baker",
    image: require("../assets/images/tree.jpg"),
    family: "Liliaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "রাইজোম এবং পাতা",
    medicinalUsed:
      "ঘা, কাশি, ব্রঙ্কাইটিস এবং মানসিক আঘাতজনিত চিকিৎসার জন্য পাতা ব্যবহার করা হয়। ক্ষত নিরাময়ের জন্য রাইজোম ব্যবহার করা হয়।",
  },
  {
    sl: 187,
    bengaliName: "‡k¦ZP›`b",
    scientificName: "Santalum album L.",
    image: require("../assets/images/tree.jpg"),
    family: "Santalaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "কাঠ এবং তেল",
    medicinalUsed:
      "গ্যাস্ট্রিক, প্রস্রাবের ব্যাধি, জ্বর, সানস্ট্রোক, হজমের সমস্যা এবং পেটের ব্যথার চিকিৎসায় চন্দন খুবই উপকারী। চন্দন কাঠের পেস্ট ত্বকের চিকিৎসার জন্য এবং ত্বকের উজ্জলতা বৃদ্ধিতে ব্যবহার করা হয়।",
  },
  {
    sl: 188,
    bengaliName: "wiVv",
    scientificName: "Sapindus mukorssi Gaertn.",
    image: require("../assets/images/tree.jpg"),
    family: "Sapindaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং বীজ",
    medicinalUsed:
      "অত্যধিক লালা নিঃসরণ, মৃগীরোগ, ক্লোরোসিস এবং জ্বরের চিকিৎসায় ফল ব্যবহার করা হয়। দাঁতের ক্ষয়রোগের চিকিৎসায় বীজ ব্যবহার করা হয়। এটি চুল ধোয়ার জন্য সাবান এবং শ্যাম্পুতে প্রধান উপাদান হিসাবে ব্যবহৃত হয়, কারণ এটি চুলের স্বাস্থ্যের জন্য ভাল বলে বিবেচিত ।",
  },
  {
    sl: 189,
    bengaliName: "A‡kvK",
    scientificName: "Saraca asoca (Roxb.) De Wilde.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল এবং ফুল",
    medicinalUsed:
      "বাকল শরীরে ইস্ট্রোজেনের মাত্রা কমায়, মহিলাদের সুঢৌল বক্ষ, পিরিয়ডের অনিয়ম, মাথাব্যথা, মেজাজের পরিবর্তন এবং ওজন বৃদ্ধির জন্য ব্যবহার করা হয়। ফুল ডায়াবেটিস নিরাময় এবং বদহজমের জন্য ব্যবহার করা হয়।",
  },
  {
    sl: 190,
    bengaliName: "MRwccyj/ gvwb cøv›U",
    scientificName: "Scindapsus officinalis (Roxb.) Schott.",
    image: require("../assets/images/tree.jpg"),
    family: "Araceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং পাতা",
    medicinalUsed:
      "শুকনো ফলের গুঁড়া হাঁপানি, গলার সংক্রমণ, অন্ত্রের পরজীবী, ডায়রিয়া, পাইলস , কোলিক এবং বদহজমের জন্য ব্যবহৃত হয়। জ্বর, বাত ও ব্যথায় পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 191,
    bengaliName: "eba‡b",
    scientificName: "Scoparia dulcis L.",
    image: require("../assets/images/tree.jpg"),
    family: "Scrophulariaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "জ্বর, কাশি, ব্রঙ্কাইটিস, ডায়াবেটিস এবং দাঁতের সমস্যায় এ বৃক্ষ ব্যবহার করা হয়।",
  },
  {
    sl: 192,
    bengaliName: "`v`g`©b",
    scientificName: "Senna alata (L.) Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Caesalpiniaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "লিভারের দাগ, রিং ওয়ার্ম এবং অন্যান্য ত্বকের রোগ থেকে মুক্তি পাওয়ার প্রতিকার হিসেবে এটি খুবই জনপ্রিয়",
  },
  {
    sl: 193,
    bengaliName: "KjKvmy‡›`",
    scientificName: "Senna sophera (L.) Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Caesalpiniaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "হাঁপানি, ব্রংকাইটিস এবং হেঁচকিতে এর পাতা ব্যবহার করা হয়। পাতার রস গনোরিয়া এবং সিফিলিটিক ঘাতে উপকারী। মূলের বাকল দাদ, পিটিরিয়াসিস এবং সোরিয়াসিসের জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 194,
    bengaliName: "eKdzj",
    scientificName: "Sesbania grandiflora Pers.",
    image: require("../assets/images/tree.jpg"),
    family: "Fabaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল, ফুল এবং পাতা",
    medicinalUsed:
      "বাকল গুটিবসন্ত এবং জ্বরের চিকিৎসায় উপকারী। এর ফুল মাথাব্যথা, নাক বন্ধ হওয়া সারাতে হয় । পাতা কৃমির উপদ্রব এবং মেনোরেজিয়া এবং আলসারেটিভ কোলাইটিসের মতো রক্তপাতজনিত রোগে সহায়ক।",
  },
  {
    sl: 195,
    bengaliName: "‡e‡ijv",
    scientificName: "Sida cordifolia L.",
    image: require("../assets/images/tree.jpg"),
    family: "Malvaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, মূল এবং ফল",
    medicinalUsed:
      "শিকড় প্রস্রাবের রোগ, রক্তপাত, পাইলস, হেমাটুরিয়া, গনোরিয়া, দীর্ঘস্থায়ী আমাশয় এবং হাঁপানি রোগে ব্যবহৃত হয়। পাইলস এ রক্তপাত বন্ধে এর ফল উপকারী। পাতা ফোড়ার জন্য ব্যবহার করা হয়।",
  },
  {
    sl: 196,
    bengaliName: "KzgvixjZv",
    scientificName: "Smilax perfoliata Lour.",
    image: require("../assets/images/tree.jpg"),
    family: "Smilacaceae",
    category: "আরোহী",
    methodOfPropagation: "উদ্ভিজ্জ",
    usedPart: "মূল এবং পাতা",
    medicinalUsed:
      "শিকড় যৌনরোগ, ত্বকের সমস্যা এবং আমাশয়ের চিকি]সার জন্য খাওয়া হয়। পাতা আলসার এবং গনোরিয়ায ব্যবহৃত হয়।",
  },
  {
    sl: 197,
    bengaliName: "wZZ‡e¸b",
    scientificName: "Solanum nigrum  L.",
    image: require("../assets/images/tree.jpg"),
    family: "Solanaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং পাতা",
    medicinalUsed:
      "হাঁপানি এবং অত্যধিক তৃষ্ণা নিরাময়ে জন্য ফল ব্যবহার করা হয় । পাতা পেট ফাঁপা, পেপটিক আলসার এবং আমাশয়ের জন্য ভালো।",
  },
  {
    sl: 198,
    bengaliName: "gvinvwU½v",
    scientificName: "Spilanthes paniculata Wall.",
    image: require("../assets/images/tree.jpg"),
    family: "Compositae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "ফুল এবং পাতা",
    medicinalUsed:
      "দাঁতের ব্যথা এবং মুখের অন্যান্য সমস্যা দূর করতে এ গাছের  ফুলের মাথা চিবিয়ে খাওয়া হয়। পাতা চর্মরোগের চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 199,
    bengaliName: "r",
    scientificName: "Sterculia foetida L.",
    image: require("../assets/images/tree.jpg"),
    family: "Sterculiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং বাকল",
    medicinalUsed:
      "বাকল ড্রপসি এবং বাত রোগের চিকিৎসায় ব্যবহৃত হয়। গনোরিয়া চিকিৎসায় বীজ ব্যবহার করা হয়।",
  },
  {
    sl: 200,
    bengaliName: "wel KPz",
    scientificName: "Steudnera clocassifolia K.Koch.",
    image: require("../assets/images/tree.jpg"),
    family: "Araceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "কন্দ",
    medicinalUsed: "কন্দ হাঁপানির চিকিৎসায় ব্যবহৃত হয়।",
  },
  {
    sl: 201,
    bengaliName: "wPwbcvZv",
    scientificName: "Stevia serrata Cav.",
    image: require("../assets/images/tree.jpg"),
    family: "Asteraceae",
    category: "বীরুৎ",
    methodOfPropagation: "কাটিং",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "খাদ্য, পানীয় বা ওষুধে চিনির বিকল্প হিসেবে বিশ্বজুড়ে এর বাণিজ্যিক মূল্য রয়েছে। এটি এমন একটি বৃক্ষ যা অল্প ক্যালোরির সাথে মিষ্টতা প্রদান করে এবং স্বাস্থ্যের উপর কোনো পার্শ্বপ্রতিক্রিয়া দেখায়না। এটি ব্যাকটেরিয়া এবং ছত্রাকের বৃদ্ধিকেও বাধা দিতে পারে।",
  },
  {
    sl: 202,
    bengaliName: "KzuwPjv",
    scientificName: "Strychnos nux-vomica L.",
    image: require("../assets/images/tree.jpg"),
    family: "Loganiaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বীজ",
    medicinalUsed:
      "বীজ অল্প মাত্রায় টনিক হিসেবে শক্তিশালী। হোমিওপ্যাথিক ওষুধে বীজের নির্যাস বেশি ব্যবহৃত হয়।",
  },
  {
    sl: 203,
    bengaliName: "‡MvjvcRvg",
    scientificName: "Syzygium jambos (L.)Alston.",
    image: require("../assets/images/tree.jpg"),
    family: "Myrtaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা, বাকল এবং ফল",
    medicinalUsed:
      "হাঁপানি, ক্লান্তি ও আমাশয়ে বাকল ব্যবহার করা হযয়। চোখের ব্যথায় এর পাতা ব্যবহার করা হযয়। ফল মস্তিষ্ক এবং লিভারের জন্য একটি টনিক হিসাবে বিবেচিত হয়।",
  },
  {
    sl: 204,
    bengaliName: "‡ZuZzj",
    scientificName: "Tamarindus indicus L.",
    image: require("../assets/images/tree.jpg"),
    family: "Leguminosae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল এবং পাতা",
    medicinalUsed:
      "পাকা ফলের পাল্প জ্বর, ডিসপেপসিয়া, গ্যাস্ট্রাইটিস, আমাশয় এবং ডায়রিয়ায় প্রতিকার। প্রদাহজনিত ফোলাভাব, টিউমার এবং দাদ কমাতে পাতার পোল্টিস প্রয়োগ করা হয়।",
  },
  {
    sl: 205,
    bengaliName: "ARy©b",
    scientificName: "Terminalia arjuna W &A",
    image: require("../assets/images/tree.jpg"),
    family: "Combretaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "বাকল",
    medicinalUsed:
      "বাকল হল কার্ডিও টনিক এবং কার্যকরভাবে হৃদস্পন্দন, এনজাইনা এবং দুর্বল করোনারি সঞ্চালনের চিকিৎসায় ব্যবহার করা হয়।",
  },
  {
    sl: 206,
    bengaliName: "e‡niv",
    scientificName: "Terminalia belerica Roxb.",
    image: require("../assets/images/tree.jpg"),
    family: "Combretaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "লিভারকে রক্ষা করতে এবং শ্বাসযন্ত্রের সংক্রমণ, কাশি এবং গলা ব্যথা সহ শ্বাসযন্ত্রের চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 207,
    bengaliName: "KvVev`vg",
    scientificName: "Terminalia catappa L.",
    image: require("../assets/images/tree.jpg"),
    family: "Combretaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল, বাকল এবং পাতা",
    medicinalUsed:
      "ফলের কার্নেল যৌন কর্মহীনতা নিরাময করে; যেমন অকাল বীর্যপাত, অতি যৌনতা এবং জলীয় বীর্য। বাকল গ্যাস্ট্রিক রোগ, পিত্তজনিত ডায়রিয়া, আমাশয় এবং পেটের ব্যথার জন্য ব্যবহৃত হয়। কচি পাতার রস কুষ্ঠরোগ, খোসপাঁচড়া এবং অন্যান্য চর্মরোগের জন্য একটি মলম প্রস্তুত করতে ব্যবহৃত হয়।",
  },
  {
    sl: 208,
    bengaliName: "nwiZwK",
    scientificName: "Terminalia chebula Retz.",
    image: require("../assets/images/tree.jpg"),
    family: "Combretaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ",
    usedPart: "ফল",
    medicinalUsed:
      "ফল হাঁপানি, কুষ্ঠরোগ, কোষ্ঠকাঠিন্য, দীর্ঘস্থায়ী আলসার এবং ক্ষত রোগে উপকারী।",
  },
  {
    sl: 209,
    bengaliName: "nj‡` Kiex/ Kj‡K dzj",
    scientificName: "Thevetia peruviana  (Pers.) K.Schum.",
    image: require("../assets/images/tree.jpg"),
    family: "Apocynaceae",
    category: "বৃক্ষ",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "বাকল",
    medicinalUsed: "বিভিন্ন ধরনের জ্বরে বাকল উপকারী।",
  },
  {
    sl: 210,
    bengaliName: "¸j",
    scientificName: "Tinospora cordifolia (Willd) Hook. f.",
    image: require("../assets/images/tree.jpg"),
    family: "Menispermaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "কান্ড এবং পাতা",
    medicinalUsed:
      "কান্ড এবং পাতা অম্লতা, জন্ডিস, দীর্ঘস্থায়ী আমাশয় এবং ডায়রিয়ার চিকিৎসার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 211,
    bengaliName: "AšÍg~j",
    scientificName: "Tylophora indica (Burm.f.) Merr.",
    image: require("../assets/images/tree.jpg"),
    family: "Asclepiadaceae",
    category: "আরোহী",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "কাশি, হাঁপানি, ব্রঙ্কাইটিস, ডায়রিয়া, বাত এবং গাউটি ব্যথার চিকিৎসার জন্য শিকড় এবং পাতা ব্যবহৃত হয়। পাতা শুকিয়ে ক্যাপসুল তৈরি করা হযয় যা আমাশয়ে কাজে লাগে।",
  },
  {
    sl: 212,
    bengaliName: "iv¯œv",
    scientificName: "Vanda tessellata  (Roxb.) Hook. Ex.G.Don",
    image: require("../assets/images/tree.jpg"),
    family: "Orchidaceae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "শিকড়",
    medicinalUsed:
      "শিকড় ডিসপেপসিয়া, ব্রঙ্কাইটিস, প্রদাহ, পাইলস এবং হেঁচকিতে উপকারী। বাহ্যিকভাবে মূলটি বাত এবং স্নায়ুতন্ত্রের রোগে ব্যবহৃত হয়।",
  },
  {
    sl: 213,
    bengaliName: "wbwk›`v",
    scientificName: "Vitex negundo L.",
    image: require("../assets/images/tree.jpg"),
    family: "Verbenaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "তীব্র বাতজনিত কারণে ফোলে উঠা এবং গনোরিয়াল এপিডিডাইমাইটিস এবং অর্কাইটিস থেকে অণ্ডকোষের ফুলে যাওযা । শিকড় একজিমা, দাদ এবং অন্যান্য চর্মরোগ, যকৃতের ব্যাধি, প্লীহার বৃদ্ধি, বাতের ব্যথা, গেঁটেবাত, ফোড়া এবং পিঠের ব্যথায ব্যবহৃত হয়।",
  },
  {
    sl: 214,
    bengaliName: "bxj-wbwk›`v",
    scientificName: "Vitex trifolia L.",
    image: require("../assets/images/tree.jpg"),
    family: "Verbenaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "পাতা এবং মূল",
    medicinalUsed:
      "শিকড় ডায়াফোরটিক এবং মূত্রবর্ধক, জ্বর এবং লিভারের রোগের চিকিৎসার জন্য ব্যবহৃত হয়। পাতা শুকনো ফোমেন্টেশন বা পোল্টিস হিসেবে ব্যবহার করা হয়। মচকে যাওয়া, কনটুশন, বাত এবং ফোলা অণ্ডকোষের চিকিৎসার জন্য এর পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 215,
    bengaliName: "gnvf…½ivR",
    scientificName: "Wedelia calendulacea  Lees.",
    image: require("../assets/images/tree.jpg"),
    family: "Compositae",
    category: "বীরুৎ",
    methodOfPropagation: "বীজ",
    usedPart: "পুরো বৃক্ষ",
    medicinalUsed:
      "চুলের বৃদ্ধির জন্য পাতা ব্যবহার করা হযয়। এটি কাশি, ত্বকের সেফালাজিয়া রোগেও ব্যবহৃত হয়।",
  },
  {
    sl: 216,
    bengaliName: "bvMgwb",
    scientificName: "Wissadula periplocifolia (L.) K.Presl",
    image: require("../assets/images/tree.jpg"),
    family: "Malvaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "পাতা",
    medicinalUsed:
      "মাকড়সার কামড় এবং মৌমাছির হুল থেকে প্রদাহের চিকিৎসায় পাতা ব্যবহার করা হয়।",
  },
  {
    sl: 217,
    bengaliName: "Ak^MÜv",
    scientificName: "Withania somnifera (L.) Dunal",
    image: require("../assets/images/tree.jpg"),
    family: "Solanaceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ",
    usedPart: "মূল, পাতা, ফল এবং বীজ",
    medicinalUsed:
      "খিঁচুনি এবং নিদ্রাহীনতায় শিকড়ের ব্যাপক ব্যবহার রয়েছে। ঘা নিরাময়ে এবং জ্বরে পাতা ব্যবহার করা হযয়। ফল মূত্রবর্ধক এবং বীজ সম্মোহনকারী; দুধ জমাট বাঁধার জন্য ব্যবহৃত হয়।",
  },
  {
    sl: 218,
    bengaliName: "`vuBdzj/ avÎxdzj",
    scientificName: "Woodfordia fruticosa Kurz",
    image: require("../assets/images/tree.jpg"),
    family: "Lythraceae",
    category: "গুল্ম",
    methodOfPropagation: "বীজ/কাটিং",
    usedPart: "ফুল এবং মূল",
    medicinalUsed:
      "শুকনো ফুল আমাশয়, পাইলস ও যকৃতের রোগে ব্যবহৃত হয় এবং গুটিবসন্তের মলম ব্যবহৃত হয়। শিকড় বাত, কটিদেশ এবং পাঁজরের ফাটল নিরাময়ে খুব কার্যকর।",
  },
  {
    sl: 219,
    bengaliName: "eb Av`v",
    scientificName: "Zingiber montanum (Koenig) Dietrich.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "H erb",
    methodOfPropagation: "রাইজোম",
    usedPart: "রাইজোম",
    medicinalUsed:
      "ডায়রিয়া এবং শূল রোগে কন্দ একটি কারমিনেটিভ এবং উদ্দীপক হিসাবে ব্যবহৃত হয়।",
  },
  {
    sl: 220,
    bengaliName: "Av`v",
    scientificName: "Zingiber officinale Rosc.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "রাইজোম",
    medicinalUsed:
      "আদা হার্টের সমস্যা নিরাময়ে, পেট খারাপ, ডায়রিয়ার চিকিৎসায় ব্যবহৃত হয়। পিত্তথলি থেকে পিত্ত নিঃসরণে উৎসাহিত করে, বাত জনিত জয়েন্টের ব্যথা কমায়, হৃদরোগ ও ফুসফুসের রোগ, উপশম কাশি এবং সর্দি, গলার সংক্রমণের জন্য উপকারী। ডায়রিয়া এবং শূল রোগে কন্দ একটি কারমিনেটিভ এবং উদ্দীপক হিসাবে ব্যবহৃত হয়।",
  },
  {
    sl: 221,
    bengaliName: "GKvw½",
    scientificName: "Zingiber zerumbet Sm.",
    image: require("../assets/images/tree.jpg"),
    family: "Zingiberaceae",
    category: "বীরুৎ",
    methodOfPropagation: "রাইজোম",
    usedPart: "রাইজোম",
    medicinalUsed:
      "রাইজোম হাঁপানি, কাশি, কৃমি, কুষ্ঠ এবং অন্যান্য চর্মরোগের চিকিৎসায় ব্যবহৃত হয়। এটি জয়েন্টের বাত ব্যথার জন্য বাহ্যিকভাবে প্রয়োগ করা হয়।",
  },
];
